odaybook/curatorship/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns

urlpatterns = patterns("odaybook.curatorship.views",
   (r'^$', 'index'),

   (r'connections/$', 'connections_list'),
   (r'connections/add/$', 'connection_edit', {'mode': 'add'}),
   (r'connections/delete/(?P<connection_id>\d+)$', 'connection_edit', {'mode': 'delete'}),

   (r'^pupil/$', 'pupil_list'),
   (r'^pupil/add/$', 'pupil_edit', {'mode': 'add'}),
   (r'^pupil/edit/(?P<id>\d+)/$', 'pupil_edit', {'mode': 'edit'}),
   (r'^pupil/delete/(?P<id>\d+)/$', 'pupil_edit', {'mode': 'delete'}),

   (r'^send-append-request/$', 'send_parent_request'),

   (r'^requests/approve/$', 'requests', {'mode': 'approve'}),
   (r'^requests/disapprove/$', 'requests', {'mode': 'disapprove'}),
)

odaybook/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
   (r'^chaining/', include('smart_selects.urls')),
   (r"^$", "odaybook.views.index"),
   (r"^grade/$", "odaybook.views.grade"),
   (r"^subjects/$", "odaybook.views.subjects"),
   (r"^teachers/$", "odaybook.views.teachers"),
   (r"^teachers/(?P<id>\d+)/$", "odaybook.views.teacher"),

   (r'^admin/doc/', include('django.contrib.admindocs.urls')),
   (r'^admin/(.*)', include(admin.site.urls)),

   (r'^accounts/', include('odaybook.userextended.urls')),
   (r'^marks/', include('odaybook.marks.urls')),
   (r'^curatorship/', include('odaybook.curatorship.urls')),
   (r'^administrator/', include('odaybook.userextended.urls')),
   (r'^attendance/', include('odaybook.attendance.urls')),
   (r'^reports/', include('odaybook.reports.urls')),
)

odaybook/curatorship/models.py
# -*- coding: UTF-8 -*-
'''
    Связки учитель<-->класс и заявки на привязку
'''

import datetime

from django.db import models
from django.core.mail import send_mail
from django.template.loader import render_to_string

from smart_selects.db_fields import SimpleChainedForeignKey

from odaybook.userextended.models import Teacher, Subject, Grade
from odaybook.userextended.models import Parent, Pupil
from django.conf import settings

GROUPS = zip(*([str(i) for i in range(1, 11)], )*2)
GROUPS.insert(0, ('0', u'Весь класс'))

class Connection(models.Model):
    '''
        Данная связка позволяет устоновить точное соответветсвие между
        учителем, предметом, классом и группой.

        Это необходимо для случаев, когда преподаватель ведёт уроки только в
        одной группе, или ведёт не все возможные предметы.
    '''
    teacher = SimpleChainedForeignKey(Teacher,
                                      ('subject', 'grade'),
                                      ('subjects', 'grades'),
                                      verbose_name = u'Учитель')
    subject = models.ForeignKey(Subject, verbose_name = u'Предмет')
    grade = models.ForeignKey(Grade, verbose_name = u'Класс')
    connection = models.CharField(verbose_name = u'Связь',
                                  max_length = 1,
                                  choices = GROUPS,
                                  default = '0')
    class Meta:
        ordering = ['teacher']
        unique_together = (('teacher', 'subject', 'grade'), )
        verbose_name = u'Связь'

class Request(models.Model):
    '''
        Заявка родителя классному руководителю на привязку ребёнка.
    '''
    parent = models.ForeignKey(Parent)
    pupil = models.ForeignKey(Pupil)
    activated = models.BooleanField()
    created_timestamp = models.DateTimeField(auto_now_add=True)
    activated_timestamp = models.DateTimeField(null = True, blank = True)

    def approve(self):
        '''
            Уведомление об одобрении заявки, сохранение.
        '''
        exists = self.parent.pupils.all()
        self.parent.pupils.add(self.pupil)
        if not exists:
            self.parent.current_pupil = self.pupil
        self.parent.save()
        self.activated = True
        self.activated_timestamp = datetime.datetime.now()
        send_mail(u'Система электронных дневников. Одобрение привязки к ученику.',
                  render_to_string('~curatorship/parent_approve_mail.html'),
                  settings['DEFAULT_FROM_EMAIL'], [self.parent.email])
        self.save()

    def disapprove(self):
        '''
            Уведомление об отклонении заявки, сохранение.
        '''
        self.activated = True
        self.activated_timestamp = datetime.datetime.now()
        send_mail(u'Система электронных дневников. Отклонение привязки к ученику.',
                  render_to_string('~curatorship/parent_disapprove_mail.html'),
                  settings['DEFAULT_FROM_EMAIL'], [self.parent.email])
        self.save()

    
    

odaybook/userextended/models.py
# -*- coding: UTF-8 -*-

from datetime import timedelta, datetime, date
import pytils
import random
import logging

from django.db import models
from django.db.models import Q
from django.db.models.aggregates import Avg
from django.contrib.auth.models import User, UserManager
from django.db.models.signals import post_save, post_syncdb
from django.dispatch import receiver

from odaybook.utils import PlaningError
from odaybook import settings

logger = logging.getLogger(__name__)

class School(models.Model):
    '''Модель для школы'''
    name = models.CharField(u"Имя учебного заведения", max_length = 250)
    saturday = models.BooleanField(verbose_name = u'Шестидневка', default = True)
    url = models.URLField(verbose_name = u'Веб-сайт', null = True, blank = True)
    address = models.CharField(verbose_name = u'Адрес школы', max_length = 255)
    phone = models.CharField(verbose_name = u'Телефон школы', max_length = 255)
    max_mark = models.IntegerField(verbose_name = u'Максимальный балл', default = 5)
    gapps_use = models.BooleanField(verbose_name = u'Использовать Google Apps', default = False)
    gapps_login = models.CharField(max_length = 255, default = '', verbose_name = u'Логин для Google Apps',
                                   blank = True, null = True)
    gapps_password = models.CharField(max_length = 255, default = '', verbose_name = u'Пароль для Google Apps',
                                      blank = True, null = True)
    gapps_domain = models.CharField(max_length = 255, default = '', verbose_name = u'Домен для Google Apps',
                                    blank = True, null = True)
    private_domain = models.CharField(max_length = 255, verbose_name = u'Система привязана к домену',
                                      null = True, blank = True)
    private_salute = models.CharField(max_length = 255, verbose_name = u'Персональное приветствие',
                                      null = True, blank = True)

    serialize_fields = ['id', 'name', 'saturday']
    serialize_name = 'school'
    
    def __init__(self, *args, **kwargs):
        '''
            Подгрузка списка доступных настроек. Необходимо в списке школ панели администратора.
        '''
        
        from odaybook.curatorship.models import Connection
        super(School, self).__init__(*args, **kwargs)
        
        grades = Grade.objects.filter(school = self).count() > 0
        teachers = Teacher.objects.filter(school = self).count() > 0
        marks = Connection.objects.filter(teacher__school = self).count() > 0
        show = {}
        show['teachers'] = show['staff'] = show['subjects'] = show['grades'] = show['options'] = True
        show['pupils'] = grades
        show['resultdates'] = grades
        show['connections'] = teachers
        show['deliveryes'] = marks
        show['timetables'] = teachers
        show['marks'] = marks
        self.show = show

    def __unicode__(self):
        return self.name
    
    def get_workdays(self):
        '''
            Список числовых значений учебных дней.
        '''
        if self.saturday:
            days = 6
        else:
            days = 5
        return range(1, days+1)

    def get_workdays_tuple(self):
        '''Возвращает кортедж из кириллических названий учебных дней школы.'''
        result = ()
        for d in settings.WORKDAYS:
            if int(d[0]) in self.get_workdays():
                result += (d, )
        return result

    def get_workdays_dict(self):
        '''
            Возвращает словарь учебных дней школы, в которых числовому значению ключа соответстветствует
            кортедж формата (ключ, кириллическое_название)
        '''
        result = {}
        for d in settings.WORKDAYS:
            if int(d[0]) in self.get_workdays():
                result[int(d[0])] = d
        return result

    def save(self, *args, **kwargs):
        '''
            Начальная инициализация школы. Добавление предметов
        '''
        pk = self.pk
        super(School, self).save(*args, **kwargs)
        if not pk:
            subjects = [u'Русский язык', u'Физкультура', u'Информатика', 
                        u'Обществознание', u'Литература', u'География', 
                        u'Химия', u'Физика', u'Биология', u'История', 
                        u'ОБЖ', u'Алгебра', u'Геометрия', u'Ин. яз.']
            
            for subject in subjects:
                Subject(school = self, name = subject).save()

class Option(models.Model):
    '''
        Модель для указания дополнительных настроек как для школы, так и для системы вцелом.
    '''
    key = models.CharField(max_length = 255, verbose_name = u'Ключ')
    key_ru = models.CharField(max_length = 255, verbose_name = u'Настройка')
    value = models.CharField(max_length = 255, verbose_name = u'Значение', null = True, blank = True)
    school = models.ForeignKey(School, verbose_name = u'Школа', null = True, blank = True)

def SystemInitCallback(sender, **kwargs):
    '''
        Callback после syncdb для создания заранее существующих настроек.
    '''
    options = [
        {'key': 'vnc_link', 'key_ru': u'Ссылка на приложение ТП', 'value': ''},
    ]
    for option in options:
        Option.objects.get_or_create(**option)

post_syncdb.connect(SystemInitCallback)

class Grade(models.Model):
    '''Классы в школах'''
    number = models.IntegerField(verbose_name = u'Порядковый номер')
    long_name = models.CharField(u"Длинное имя", max_length = 100)
    small_name = models.CharField(u"Короткое имя", max_length = 10, blank = True)
    school = models.ForeignKey(School, verbose_name = "Школа")

    serialize_fields = ['id', 'long_name', 'school_id']
    serialize_name = 'grade'
    
    def __unicode__(self):
        if self.number:
            return "%d %s" % (self.number, self.long_name)
        else:
            return self.long_name

    def get_subjects(self):
        '''
            Получение списка всех предметов, которые ведутся в этом классе
        '''
        from odaybook.curatorship.models import Connection
        return [c.subject for c in Connection.objects.filter(grade = self)]

    def get_subjects_queryset(self):
        u'''
            Получение queryset всех предметов, которые ведут в этом классе
        '''
        return Subject.objects.filter(id__in = [s.id for s in self.get_subjects()])
        
    def delete(self):
        if not Pupil.objects.filter(grade = self):
            for teacher in Teacher.objects.filter(grade = self):
                teacher.grade = None
                teacher.save()
            for teacher in Teacher.objects.filter(grades = self):
                teacher.grades.remove(self)
                teacher.save()
            super(Grade, self).delete()
        else:
            raise PlaningError(u"В классе числятся ученики")
        
    def save(self, *args, **kwargs):
        self.long_name = self.long_name.lower()
        self.small_name = self.small_name.lower()
        super(Grade, self).save(*args, **kwargs)

    class Meta:
        ordering = ['number']
    
    def get_pupils_for_teacher_and_subject(self, teacher, subject):
        '''
            В свойство pupils записываются ученики, у которых преподаватель teacher ведёт предмет subject.
        '''
        from odaybook.curatorship.models import Connection
        conn = Connection.objects.filter(teacher = teacher, grade = self, subject = subject)
        if not conn:
            raise PlaningError(u'нет учеников')
        conn = conn[0]
        if conn.connection == '0':
            self.pupils = Pupil.objects.filter(grade = self)
        else:
            pupil_connections = PupilConnection.objects.filter(pupil__grade = self,
                                                               subject = subject,
                                                               value = conn.connection)
            self.pupils = Pupil.objects.filter(id__in = [c.pupil.id for c in pupil_connections])

class Subject(models.Model):
    '''Учебная дисциплина'''
    name = models.CharField(u"Наименование", max_length = 100)
    school = models.ForeignKey(School, verbose_name = "Школа")
    groups = models.CharField(max_length = 1, blank = True, null = True, verbose_name = u'Количество групп')


    def __unicode__(self):
        return self.name
    def delete(self):
        for teacher in Teacher.objects.filter(subjects = self):
            teacher.subjects.remove(self)
            teacher.save()
        super(Subject, self).delete()

    def get_groups(self):
        '''Возвращает список из номеров групп для данного предмета'''
        return range(1, int(self.groups)+1)

    class Meta:
        ordering = ['name']

class SearchManager(models.Manager):
    '''
        Универсальный менеджер для поиска по произвольным полям модели. Заменяет стандартный objects.

        При инициализации передается список полей для поиска.
    '''
    def __init__(self, search_fields = []):
        self.search_fields = search_fields
        models.Manager.__init__(self)

    def search(self, search_string):
        '''
            Собственно поиск.

            search_string - строка для поиска.
        '''
        search_query_list = [Q(**{s + '__icontains': search_string}) for s in self.search_fields]
        search_query = reduce(lambda x, y: x | y, search_query_list)
        return self.filter(search_query)

class ClerkManager(UserManager, SearchManager):
    '''Аггрегация всего и вся'''
    pass

class BaseClerk(models.Model):
    '''
        Поля, присыщие всем пользовательским моделям, включая концентрациооную BaseUser.
    '''
    middle_name = models.CharField(u"Отчество", max_length = 30)
    cart = models.CharField(u'Карта', max_length = 10, null = True, blank = True)
    phone = models.CharField(max_length = 20, verbose_name = u'Номер телефона', null = True, blank = True)
    roles = models.ManyToManyField('BaseUser', null = True, blank = True,

odaybook/curatorship/forms.py
# -*- coding: UTF-8 -*-
'''
    Формы из этого модуля могут заимствоваться другими.
'''

from django import forms
from models import Connection
from odaybook.userextended.models import Pupil, Subject, Teacher, Grade

class ConnectionForm(forms.ModelForm):
    '''
        Редактирование связок
    '''
    class Meta:
        model = Connection
        fields = ('teacher', 'subject', 'grade', 'connection')
    def __init__(self, grade__school, grade = None, *args, **kwargs):
        super(ConnectionForm, self).__init__(*args, **kwargs)
        kwargs = {'school': grade__school}
        if grade:
            self.fields['teacher'].queryset = Teacher.objects.filter(grades = grade, **kwargs)
        self.fields['subject'].queryset = Subject.objects.filter(**kwargs)
        self.fields['grade'].queryset = Grade.objects.filter(**kwargs)
        if grade:
            del self.fields['grade']
        self.grade = grade

    def save(self, *args, **kwargs):
        result = super(ConnectionForm, self).save(commit = False)
        if self.grade:
            result.grade = self.grade
        result.save()
        return result
        
class PupilForm(forms.ModelForm):
    '''
        Редактирование ученика *классным руководителем*
    '''
    class Meta:
        model = Pupil
        fields = [
                'last_name', 'first_name', 'middle_name', 'email', 'phone',
                'sex', 'special', 'order', 'health_group', 'health_note',
                'parent_phone_1', 'parent_phone_2',
        ]

class ParentRequestForm(forms.Form):
    '''
        Форма, которую заполняет родитель, для прикрепления ребёнка.
    '''
    last_name = forms.CharField(label = u'Фамилия', required=True)
    first_name = forms.CharField(label = u'Имя', required=True)
    middle_name = forms.CharField(label = u'Отчество', required=True)

    pupil = None

    def clean(self, *args, **kwargs):
        super(ParentRequestForm, self).clean(*args, **kwargs)
        if not self.errors:
            pupil_get_kwargs = {'grade': self.grade}
            pupil_get_kwargs.update(self.cleaned_data)
            if Pupil.objects.filter(**pupil_get_kwargs).exclude(
                    id__in = [p.id for p in self.parent.pupils.all()]):
                self.pupil = Pupil.objects.get(**pupil_get_kwargs)
            else:
                raise forms.ValidationError(u'Ученик не найден или уже прикреплён к вам')

    def __init__(self, grade, parent = None, *args, **kwargs):
        super(ParentRequestForm, self).__init__(*args, **kwargs)
        self.grade = grade
        self.parent = parent

odaybook/curatorship/templates/connectionWizard.html
{% extends 'curatorship_page.html' %}

{% block content %}
	<form method="post" action=".">{% csrf_token %}
		<table>
			{{ form }}
			<tr>
				<td><input type="submit"></td>
			</tr>
		</table>
	</form>
{% endblock %}

odaybook/curatorship/templates/connectionsList.html
{% extends 'curatorship_page.html' %}

{% block content %}
	<a href="/curatorship/connections/add/" class="title">Добавить связку</a>
	<table>
	<thead>
		<th>Преподаватель</th>
		<th>Предмет</th>
		<th>Тип связи</th>
		<th></th>
	</thead>
	{% for connection in connections %}
		<tr class="{% cycle 'gray' '' %}">
			<td>{{ connection.teacher.fio }}</td>
			<td>{{ connection.subject }}</td>
			<td>{{ connection.get_connection_display|lower }}</td>
			<td><a href="/curatorship/connections/delete/{{ connection.id }}" class="delete">удалить</a></td>
		</tr>
	{% endfor %}
	</table>
{% endblock %}

odaybook/curatorship/templates/curatorship_page.html
{% extends 'page.html' %}

{% block padding %}
	{% if SM == "connections" %}<h1>Связки</h1> {% else %}<a href="/curatorship/connections/">Связки</a>{% endif %}
	{% if SM == "pupil" %}<h1>Ученики</h1> {% else %}<a href="/curatorship/pupil/">Ученики</a>{% endif %}
{% endblock %}

odaybook/curatorship/templates/graphiks.html
{% extends 'curatorship/page.html' %}

{% block content %}
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["areachart"]});
      //google.setOnLoadCallback(drawChart);
    </script>

<form method="post" action=".">{% csrf_token %}
	<table>
		{% for field in form %}
		<tr>
			<td class="label"><label for="{{ field.label }}">{{ field.label_tag }}:</label></td>
			<td>{{ field }}</td>
			<td>
				{% if field.errors %}<div class="error_text">{{ field.errors }}</div>{% endif %}
				{% if field.help_text %}<div class="help_text">{{ field.help_text}}</div>{% endif %}
			</td>
		</tr>
		{% endfor %}
		<tr>
			<td colspan="2">
				<input type="submit">
			</td>
		</tr>
	</table>
</form>
{% for pupil in pupils %}
	<div id="chart{{ pupil.id }}"></div>
    <script type="text/javascript">
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Даты');
		{% for subject in subjects %}
	        data.addColumn('number', '{{ subject }}');
		{% endfor %}
        data.addRows([
						{% for date in pupil.dates %}
							[{{ date|safe }}],
						{% endfor %}
					]);
        var chart = new google.visualization.AreaChart(document.getElementById('chart{{ pupil.id }}'));
        chart.draw(data, {width: 700, height: 400, legend: 'right', title: '{{ pupil.get_full_name }}'});
    </script>
	<br />

{% endfor %}
<div id="chart_div">
	
</div>
{% endblock %}

odaybook/curatorship/templates/index.html
{% extends 'curatorship_page.html' %}

odaybook/curatorship/templates/parent_disapprove_mail.html
Здравствуйте!

Привязка к ученику не одобрена классным руководителем. Возможно, вам стоит связаться с классным руководителем и повторить заявку.

odaybook/curatorship/templates/parent_request_approve_mail.html
Здравствуйте!

Привязка к ученику одобрена классным руководителем. Можете приступать к работе.

odaybook/curatorship/templates/pupil.html
{% extends 'curatorship_page.html' %}

{% block content %}
<form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
<table class="table"><tr><td>
	<fieldset>
		<legend>Общая информация</legend>
		<table>
			<tr>
				<td class="label"><label for="id_last_name">Фамилия:</label></td>
				<td>{{ form.last_name }}</td>
				<td>
					{% if form.last_name.errors %}<div class="error_text">{{ form.last_name.errors }}</div>{% endif %}
					{% if form.last_name.help_text %}<div class="help_text">{{ form.last_name.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_first_name">Имя:</label></td>
				<td>{{ form.first_name }}</td>
				<td>
					{% if form.first_name.errors %}<div class="error_text">{{ form.first_name.errors }}</div>{% endif %}
					{% if form.first_name.help_text %}<div class="help_text">{{ form.first_name.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_middle_name">Отчество:</label></td>
				<td>{{ form.middle_name }}</td>
				<td>
					{% if form.middle_name.errors %}<div class="error_text">{{ form.middle_name.errors }}</div>{% endif %}
					{% if form.middle_name.help_text %}<div class="help_text">{{ form.middle_name.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_sex">Пол:</label></td>
				<td>{{ form.sex }}</td>
				<td>
					{% if form.sex.errors %}<div class="error_text">{{ form.sex.errors }}</div>{% endif %}
					{% if form.sex.help_text %}<div class="help_text">{{ form.sex.help_text }}</div>{% endif %}
				</td>
			</tr>
		</table>
	</fieldset>
	</td></tr><tr><td>
	<fieldset>
		<legend>Родители</legend>
		<table>
			<tr>
				<td class="label"><label for="id_special">Телефон отца:</label></td>
				<td>{{ form.parent_phone_1 }}</td>
				<td>
					{% if form.parent_phone_1.errors %}<div class="error_text">{{ form.parent_phone_1.errors }}</div>{% endif %}
					{% if form.parent_phone_1.help_text %}<div class="help_text">{{ form.parent_phone_1.help_text }}</div>{% endif %}
			</td>
			</tr>
			<tr>
				<td class="label"><label for="id_cart">Телефон матери: </label></td>
				<td>{{ form.parent_phone_2 }}
				<td>
					{% if form.parent_phone_2.errors %}<div class="error_text">{{ form.parent_phone_2.errors }}</div>{% endif %}
					{% if form.parent_phone_2.help_text %}<div class="help_text">{{ form.parent_phone_2.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_cart">Электропочта: </label></td>
				<td>{{ form.email }}
				<td>
					{% if form.email.errors %}<div class="error_text">{{ form.email.errors }}</div>{% endif %}
					{% if form.email.help_text %}<div class="help_text">{{ form.email.help_text }}</div>{% endif %}
				</td>
			</tr>
		</table>
	</fieldset>
</td></tr><tr><td>
	<fieldset>
		<legend>Другая информация</legend>
		<table>
			<tr>
				<td class="label"><label for="id_special">Спец. группа:</label></td>
				<td>{{ form.special }}</td>
				<td>
					{% if form.special.errors %}<div class="error_text">{{ form.special.errors }}</div>{% endif %}
					{% if form.special.help_text %}<div class="help_text">{{ form.cpecial.help_text }}</div>{% endif %}
			</td>
			</tr>
			<tr>
				<td class="label"><label for="id_special">{{ form.order.label }}:</label></td>
				<td>{{ form.order }}</td>
				<td>
					{% if form.order.errors %}<div class="error_text">{{ form.order.errors }}</div>{% endif %}
					{% if form.order.help_text %}<div class="help_text">{{ form.order.help_text }}</div>{% endif %}
			</td>
			</tr>
			<tr>
				<td class="label"><label for="id_special">{{ form.health_group.label }}:</label></td>
				<td>{{ form.health_group }}</td>
				<td>
					{% if form.health_group.errors %}<div class="error_text">{{ form.health_group.errors }}</div>{% endif %}
					{% if form.health_group.help_text %}<div class="help_text">{{ form.health_group.help_text }}</div>{% endif %}
			</td>
			</tr>
			<tr>
				<td class="label"><label for="id_special">{{ form.health_note.label }}:</label></td>
				<td>{{ form.health_note }}</td>
				<td>
					{% if form.health_note.errors %}<div class="error_text">{{ form.health_note.errors }}</div>{% endif %}
					{% if form.health_note.help_text %}<div class="help_text">{{ form.health_note.help_text }}</div>{% endif %}
			</td>
			</tr>
			{% if form.cart %}
				<tr>
					<td class="label"><label for="id_cart">Номер карты: </label></td>
					<td>{{ form.cart }}
					<td>
						{% if form.cart.errors %}<div class="error_text">{{ form.cart.errors }}</div>{% endif %}
						{% if form.cart.help_text %}<div class="help_text">{{ form.cart.help_text }}</div>{% endif %}
					</td>
				</tr>
			{% endif %}
		</table>
	</fieldset>
</td></tr>{% if groups %}<tr><td>
	<fieldset>
		<legend>Группы</legend>
		<table>
            {% for group in groups %}
			<tr>
				<td class="label"><label for="{{ group.value.id }}">{{ group.value.label }}</label></td>
				<td>{{ group.value }}</td>
				<td>
					{% if group.value.errors %}<div class="error_text">{{ group.value.errors }}</div>{% endif %}
					{% if group.value.help_text %}<div class="help_text">{{ group.value.help_text }}</div>{% endif %}
			    </td>
			</tr>
            {% endfor %}
		</table>
	</fieldset>

</td></tr>{% endif %}
<tr><td><input type="submit"></td></tr>
</table>
</form>
{% endblock %}

odaybook/curatorship/templates/pupilList.html
{% extends 'curatorship_page.html' %}

{% block content %}
<a href="add/" class="title">Добавить ученика</a>
<table>
	<thead>
		<th>Ученик</th>
		{#<th>Логин</th>#}
		<th>Действия</th>
	</thead>
	{% for pupil in pupils %}
	<tr>
		<td>{{ pupil.fi }}</td>
		{#<td>{{ pupil.username }}</td>#}
		<td><a href="edit/{{ pupil.id }}/">редактировать</a>, <a href="delete/{{ pupil.id }}/" class="delete">удалить</a>.</td>
	</tr>
	{% endfor %}
</table>
{% load pytils_numeral %}
<p>
	Всего {{ pupils|length }} {{ pupils|length|choose_plural:pupil_plural }}.
</p>
{% endblock %}

odaybook/curatorship/templates/pupilPasswords.html
{% extends 'curatorship_page.html' %}

{% block content %}
<table class="print">
	{% for pupil in pupils %}
	<tr>
		<td>{{ pupil.fi}}</td>
		<td>{{ pupil.username }}</td>
		<td>{{ pupil.password }}</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

odaybook/curatorship/templates/pupilPasswordsList.html
{% extends 'curatorship_page.html' %}

{% block content %}
<form method="post" action=".">{% csrf_token %}
<input type="submit" value="Генерировать пароль" class="title" />
	<table>
		<thead>
			<th><input type="checkbox" onclick="if($(this).attr('checked')) $('input.pupil').attr('checked', 'true'); else $('input.pupil').attr('checked', '')" /></th>
			<th>Фамилия, имя</th>
			<th>Логин</th>
		</thead>
		{% for pupil in pupils %}
		<tr>
			<td><input type="checkbox" id="pupil-{{ pupil.id }}" class="pupil" name="pupil-{{ pupil.id }}" /></td>
			<td><label for="pupil-{{ pupil.id }}">{{ pupil.fi }}</label></td>
			<td>{{ pupil.username }}</td>
		</tr>
		{% endfor %}
	</table>
</form>
{% endblock %}

odaybook/curatorship/templates/send_append_request.html
{% extends 'page.html' %}

{% block content %}
    {% if step == 1 %}
        <p><b>Выберите школу из списка:</b></p>
        <table class="no-hover">
            {% for obj in objects %}
                <tr><td><a href="?school={{ obj.id }}">{{ obj }}</a></td></tr>
            {% endfor %}
        </table>
    {% endif %}

    {% if step == 2 %}
        <p><b>Выберите класс:</b></p>
        <table class="no-hover">
            {% for obj in objects %}
                <tr><td><a href="?school={{ school.id }}&grade={{ obj.id }}">{{ obj }}</a></td></tr>
            {% endfor %}
        </table>
    {% endif %}

    {% if step == 3 %}
        <p>Введите информацию о своём ребёнке</p>
        
        <form method="post" action="?school={{ school.id }}&grade={{ grade.id }}">{% csrf_token %}
            <table class="no-hover">
                {{ form }}
                <tr>
                    <td colspan="2"><input type="submit" value="Отправить" /></td>
                </tr>
            </table>
        </form>
    {% endif %}
    {% if step == 4 %}
        <p>Ожидайте подтверждения классным руководителем. Вы получите уведомление по электронной почте.</p>

    {% endif %}
{% endblock %}