odaybook/marks/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns

urlpatterns = patterns("odaybook.marks.views",
                       (r'^$', 'index'),
                       (r'set_current_subject/(?P<subject_id>\d+)', 'set_current_subject'),

                       (r'^subject/(?P<subject_id>\d+)/', 'marksView'),

                       )

odaybook/reports/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns

urlpatterns = patterns("odaybook.reports.views",
                       (r'^$', 'index'),
                       (r'^health/$', 'report_health'),
                       (r'^order/$', 'report_order'),
                       (r'^fillability/$', 'report_fillability'),
                       (r'^membershipchanges/$', 'report_membershipchanges'),
                       (r'^marks/$', 'report_marks'),
                       (r'^marks/(?P<id>\d+)/$', 'view_marks'),
                       (r'^marks/result/$', 'report_marks', {'mode': 'result'}),
                       )

odaybook/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
   (r'^chaining/', include('smart_selects.urls')),
   (r"^$", "odaybook.views.index"),
   (r"^grade/$", "odaybook.views.grade"),
   (r"^subjects/$", "odaybook.views.subjects"),
   (r"^teachers/$", "odaybook.views.teachers"),
   (r"^teachers/(?P<id>\d+)/$", "odaybook.views.teacher"),

   (r'^admin/doc/', include('django.contrib.admindocs.urls')),
   (r'^admin/(.*)', include(admin.site.urls)),

   (r'^accounts/', include('odaybook.userextended.urls')),
   (r'^marks/', include('odaybook.marks.urls')),
   (r'^curatorship/', include('odaybook.curatorship.urls')),
   (r'^administrator/', include('odaybook.userextended.urls')),
   (r'^attendance/', include('odaybook.attendance.urls')),
   (r'^reports/', include('odaybook.reports.urls')),
)

odaybook/marks/models.py
# -*- coding: UTF-8 -*-
'''
    Работа с оценками.
'''


from django.db import models
from odaybook.userextended.models import Pupil, Teacher, Subject, Grade, School

class Lesson(models.Model):
    '''
        Занятие. Содержит информацию об уроке. 
    '''
    teacher = models.ForeignKey(Teacher,
                                verbose_name = u'Учитель',
                                blank = True,
                                null = True)
    date = models.DateField(u'Дата')
    topic = models.CharField(u'Тема урока',
                             max_length = 200,
                             blank = True,
                             null = True)
    task = models.CharField(u'Домашнее задание',
                            max_length = 200,
                            blank = True,
                            null = True)
    subject = models.ForeignKey(Subject, verbose_name = u'Предмет')
    grade = models.ManyToManyField(Grade, verbose_name = u'Класс')
    file = models.FileField(verbose_name = u'Приложить файл',
                            null = True,
                            blank = True,
                            upload_to = 'lessons')
    resultdate = models.ForeignKey('ResultDate', null = True, blank = True)
    fullness = models.BooleanField(default = False)

    serialize_fields = ['id', 'teacher_id', 'date', 'topic',
                        'task', 'subject_id', 'grade']
    serialize_name = 'lesson'
    
    class Meta:
        ordering = ['-date']

    def save(self, safe = False, *args, **kwargs):
        if not safe and not self.fullness:
            if self.topic and Mark.objects.filter(lesson = self).count() > 4:
                self.fullness = True
        super(Lesson, self).save(*args, **kwargs)

class Mark(models.Model):
    '''
        Оценка или пропуск за 1 урок.
    '''
    pupil = models.ForeignKey(Pupil, verbose_name = u'Ученик')
    lesson = models.ForeignKey(Lesson, verbose_name = u'Занятие')
    mark = models.IntegerField(u'Отметка', blank = True, null = True)
    absent = models.BooleanField(u'Отсутствовал')
    date = models.DateTimeField(u'Дата выставления', auto_now_add = True)
    comment = models.TextField(u'Комментарий к отметке', blank = True)

    serialize_fields = ['id', 'pupil_id', 'lesson_id', 'mark', 'absent', 'date']
    serialize_name = 'mark'
    
    def get_type(self):
        '''
            Для выделение класса с помощью CSS.
        '''
        if self.absent:
            return "bad"
        elif self.mark < 3:
            return "bad"
        elif self.mark >= 4:
            return "good"
        else:
            return "normal"
    
    def __unicode__(self):
        if self.absent:
            return u'H'
        else:
            return unicode(self.mark)

    def save(self, *args, **kwargs):
        from odaybook.userextended.models import Notify
        if not self.lesson.fullness:
            if self.lesson.topic and Mark.objects.filter(lesson = self.lesson) > 4:
                self.lesson.fullness = True
                self.lesson.save(safe = True)
        super(Mark, self).save(*args, **kwargs)
        Notify.objects.filter(user = self.lesson.teacher, type = '1').delete()
    
    class Meta:
        ordering = ['-date']

class ResultDate(models.Model):
    '''
        Итоговый период. 
    '''
    school = models.ForeignKey(School, null = True, blank = True)
    name = models.CharField(max_length=255, verbose_name = u'Имя периода',
                            null = True, blank = True)
    date = models.DateField(verbose_name = u'Дата подведения итога')
    grades = models.ManyToManyField(Grade, verbose_name = u'Классы')

    def save(self, *args, **kwargs):
        pk = self.pk
        super(ResultDate, self).save(*args, **kwargs)
        if not self.school and not pk:
            for school in School.objects.all():
                ResultDate(school = school, name = self.name, date = self.date).save()

    class Meta:
        ordering = ['date']
    def __unicode__(self):
        return self.name

odaybook/marks/forms.py
# -*- coding: UTF-8 -*-
'''
    Большая часть форм реализованы общими средствами Django для работы с HTTP
'''

from datetime import date, timedelta

from django import forms

from models import Lesson
from odaybook.marks.models import ResultDate
from odaybook.userextended.models import Grade

class LessonForm(forms.ModelForm):
    '''
        Работа с уроком. Не факт, что используется.
    '''
    class Meta:
        model = Lesson
        fields = ['topic', 'task']

class StatForm(forms.Form):
    '''
        Универсальная форма для выбора диапазона дат статистики.
        Используется в различных приложениях.
    '''
    def __init__(self, *args, **kwargs):
        super(StatForm, self).__init__(*args, **kwargs)
        self.fields['start'].widget.format = '%d.%m.%Y'
        self.fields['end'].widget.format = '%d.%m.%Y'
    start = forms.DateField(('%d.%m.%Y', '%d.%m.%y'),
                            label = u'Дата начала периода',
                            initial = date.today() - timedelta(weeks = 2))
    end = forms.DateField(('%d.%m.%Y','%d.%m.%y'),
                          label = u'Дата окончания периода',
                          initial = date.today())


class ResultDateForm(forms.ModelForm):
    '''
        Форма для создания итоговых оценок.
    '''
    def __init__(self, school = None, *args, **kwargs):
        super(ResultDateForm, self).__init__(*args, **kwargs)
        self.school = school
        self.fields['grades'].widget = forms.CheckboxSelectMultiple()
        self.fields['grades'].help_text = ''
        self.fields['grades'].queryset = Grade.objects.filter(school = school)
        self.fields['date'].widget.format = '%d.%m.%Y'
        if not school:
            del self.fields['grades']
    class Meta:
        model = ResultDate
        fields = ['name', 'date', 'grades']
    def save(self):
        result = super(ResultDateForm, self).save(commit = False)
        result.school = self.school
        result.save()
        self.save_m2m()
        return result
    date = forms.DateField(('%d.%m.%y', '%d.%m.%Y',), label = u'Дата подведения итога')

odaybook/reports/forms.py
# -*- coding: utf-8 -*-

from django import forms

from odaybook.userextended.models import School

class SchoolSelectForm(forms.Form):
    '''
        По мелочи. 
    '''
    school = forms.ModelChoiceField(queryset = School.objects.all(), required = True, empty_label = u'Все школы')

odaybook/marks/views.py
# -*- coding: UTF-8 -*-
from datetime import date, timedelta

from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib import messages

from odaybook.userextended.models import Pupil, Subject, Grade
from odaybook.curatorship.models import Connection
from odaybook.attendance.models import UsalTimetable

from models import Lesson, Mark, ResultDate
from forms import LessonForm, StatForm

@login_required
def index(request):
    '''
        Очень обширная страница, необходимо сделать разделение. 
    '''
    render = {}
    if request.user.type == 'Parent':
        start = date.today() - timedelta(weeks = 2)
        end = date.today() + timedelta(days = 1)
        if request.method == 'GET':
            render['form'] = form = StatForm()
        else:
            render['form'] = form = StatForm(request.POST)
            if form.is_valid():
                start = form.cleaned_data['start']
                end = form.cleaned_data['end']

        render.update(request.user.current_pupil.get_all_marks(start, end))

    elif request.user.type == 'Teacher':
        import demjson

        if request.GET.get('set_current_grade', False):
            grade = get_object_or_404(Grade,
                                      id = request.GET.get('set_current_grade'))
            if grade not in request.user.grades.all():
                raise Http404(u'Нет такого класса')
            request.user.current_grade = grade
            request.user.save()
        
        render['lesson_form'] = LessonForm()
        if request.GET.get('set_lesson', False):
            lesson = get_object_or_404(Lesson,
                                       id = int(request.GET.get('lesson', 0)),
                                       teacher = request.user)
            form = LessonForm(request.GET, instance = lesson)
            if form.is_valid():
                form.save()
            return HttpResponse('ok')
        
        if request.GET.get('get_lesson_info', False):
            lesson = get_object_or_404(Lesson,
                                       id = int(request.GET.get('lesson', 0)),
                                       teacher = request.user)
            return HttpResponse(demjson.encode({'task': lesson.task or '',
                                                'topic': lesson.topic or ''}))
            
        
        if request.GET.get('set_mark', False):
            from templatetags.marks_chart import get_mark
            pupil = get_object_or_404(Pupil,
                                      id = int(request.GET.get('pupil', 0)),
                                      grade = request.user.current_grade)
            lesson = get_object_or_404(Lesson,
                                       id = int(request.GET.get('lesson', 0)),
                                       teacher = request.user)
            mark = unicode(request.GET.get('mark', 0)).lower()
            Mark.objects.filter(pupil = pupil, lesson = lesson).delete()
            m = Mark(pupil = pupil, lesson = lesson)
            tr_id = 'p-%d-%d' % (pupil.id, lesson.id)
            if mark not in ['1', '2', '3', '4', '5', 'n', u'н', '']:
                return HttpResponse(demjson.encode({'id': tr_id, 'mark': 'no'}))
            if mark == '':
                return HttpResponse(demjson.encode({'id': tr_id, 'mark': ''}))
            if mark in [u'n', u'н']:
                m.absent = True
            else:
                m.mark = int(mark)
            m.save()
            return HttpResponse(demjson.encode({'id': tr_id,
                                                'mark': get_mark(pupil, lesson),
                                                'mark_value': str(m).strip(),
                                                'mark_type': m.get_type()
                                                }, encoding = 'utf-8'))
        
        from pytils import dt
        if not request.user.current_grade:
            if request.user.get_grades():
                request.user.current_grade = request.user.get_grades()[0]
                request.user.save()
            else:
                messages.error(request, u'К вам не привязано классов')
                return HttpResponseRedirect('/')
        request.user.current_grade.get_pupils_for_teacher_and_subject(
                request.user, request.user.current_subject
        )
        
        try:
            day, month, year = request.GET.get('date', '').split('.')
            date_start = date(day = day, month = month, year = year)
        except ValueError:
            date_start = date.today()

        lessons_range = []
        render['monthes'] = monthes = {}
        for i in xrange(1, 13):
            monthes[i] = ('', 0)
        
        kwargs = {
            'subject': request.user.current_subject,
            'grade': request.user.current_grade
        }
        conn = Connection.objects.filter(teacher = request.user, **kwargs)
        if not conn:
            raise Http404('No connections')
        conn = conn[0]
        if conn.connection != '0':
            kwargs['group'] = conn.connection

        kwargs4lesson = {}
        for i in xrange(14, -1, -1):
            d = date_start - timedelta(days = i)
            kwargs['workday'] = str(d.weekday()+1)
            if UsalTimetable.objects.filter(**kwargs):
                kwargs4lesson = {'teacher': request.user,
                                 'date': d,
                                 'subject': request.user.current_subject}
                groups = {}
                for lesson in UsalTimetable.objects.filter(**kwargs):
                    groups[lesson.group] = groups.get(lesson.group, 0) + 1
                groups = groups.values()
                if Lesson.objects.filter(grade = request.user.current_grade, **kwargs4lesson).count() != max(groups):
                    for j in xrange(max(groups) - Lesson.objects.filter(**kwargs4lesson).count()):
                        t = Lesson(**kwargs4lesson)
                        t.save()
                        t.grade.add(request.user.current_grade)
                        t.save()
            resultdates = ResultDate.objects.filter(date = d, grades = request.user.current_grade)
            if resultdates:
                resultdate = resultdates[0]
                kwargs4lesson = {
                    'resultdate': resultdate,
                    'grade': request.user.current_grade,
                    'subject': request.user.current_subject,
                    'teacher': request.user
                }
                if not Lesson.objects.filter(**kwargs4lesson):
                    del kwargs4lesson['grade']
                    lesson = Lesson(topic = resultdate.name,
                                    date = resultdate.date,
                                    **kwargs4lesson)
                    lesson.save()
                    lesson.grade.add(request.user.current_grade)
                    lesson.save()

        if len(kwargs4lesson) == 0:
            raise Http404(u'Нет расписания')

        del kwargs4lesson['date']
        kwargs4lesson['date__gte'] = date_start - timedelta(days = 15)
        for lesson in Lesson.objects.filter(**kwargs4lesson).order_by('date'):
            monthes[lesson.date.month] = (dt.ru_strftime(u'%B', lesson.date),
                                          monthes[lesson.date.month][1] + 1)
            lessons_range.append(lesson)

        for i in monthes.keys():
            if monthes[i][1] == 0:
                del monthes[i]
        render['lessons'] = lessons_range
        
    return render_to_response(
            '~marks/%s/index.html' % request.user.type.lower(),
            render,
            context_instance = RequestContext(request))

@login_required
@user_passes_test(lambda u: u.type == 'Teacher')
def set_current_subject(request, subject_id):
    '''
        Установка текущего предмета учителя для работы с журналом.
    '''
    request.user.current_subject = Subject.objects.get(id = subject_id)
    request.user.save()
    next_url = request.GET.get('next', '/marks/').strip()
    return HttpResponseRedirect(next_url)

@login_required
def marksView(request, subject_id):
    '''
        Просмотр оценок по данному предмету. Для родительского интерфейса
    '''
    render = {}
    objects = Mark.objects.filter(
            pupil = request.user.current_pupil,
            lesson__subject = get_object_or_404(Subject, id=subject_id)
    ).order_by('-lesson__date')

    paginator = Paginator(objects, settings.PAGINATOR_OBJECTS)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        render['objects'] = paginator.page(page)
    except:
        render['objects'] = paginator.page(paginator.num_pages)

    render['paginator'] = paginator.num_pages - 1
    request.user.current_subject = int(subject_id)
    return render_to_response('~marks/pupil/marks.html',
                              render,
                              context_instance=RequestContext(request))

odaybook/reports/templates/index.html
{%  extends '~reports/page.html' %}

{% block content %}
    <p>Выберите отчёт из меню выше.</p>
{% endblock %}

odaybook/reports/templates/marks.html
{% load formater %}


<table class="table sort">
  <thead>
  <tr>
    <th class="active">Предметы</th>
	{% for date in dates %}
	    <th style="padding-right: 10px;">
            {% if date.resultdate %}
                {{ date.resultdate }}
            {% else %}
                {{ date|date:"d.m" }}
            {% endif %}
        </th>
	{% endfor %}
    <th>Средний балл</th>
    <th>Учителя</th>
  </tr>
  </thead>

  <tbody>

	{% for subject in marks %}
		<tr class="{% cycle 'gray' '' %}">
			<td>
                {% if user.type == 'Parent' %}
                    <a href="/reports/marks/{{ subject.0.id }}/">{{ subject.0 }}</a>
                {% else %}
                    {{ subject.0 }}
                {% endif %}
            </td>
			{% for mark in subject.1 %}
				<td>
                    {% for m in mark %}<div class="mark-{{ m.get_type }}" style="display:inline">{{ m }}</div>{% if not forloop.last %},&nbsp;{% endif %}{% endfor %}
                </td>
			{% endfor %}
			<td><div class="mark-{{ subject.4 }}">{{ subject.2|floatformat:"-2"|number_format }}</div></td>
    		<td><div class="teacher">
                {% if user.type == 'Parent' %}
                    <a href="/teachers/{{ subject.3.id }}/">{{ subject.3.fio|default:"не указан" }}</a>
                {% else %}
                    {{ subject.3.fio|default:"не указан" }}
                {% endif %}
            </div></td>
		</tr>
	{% endfor %}

  </tbody>
</table>

odaybook/reports/templates/page.html
{%  extends 'page.html' %}

{% load formater %}

{% block padding %}
    {% if user.type == 'Teacher' %}
        {% padding_menu_block 'Группы здоровья' '/reports/health/' SM %}
        {% padding_menu_block 'Социальные группы' '/reports/order/' SM %}
        {% padding_menu_block 'Оценки' '/reports/marks/' SM %}
    {%  endif %}
    {%  if user.type == 'Superviser' %}
        {% padding_menu_block 'Заполненность' '/reports/fillability/' SM %}
        {% padding_menu_block 'Зачисления и исключения' '/reports/membershipchanges/' SM %}
        {% padding_menu_block 'Оценки' '/reports/marks/' SM %}
    {%  endif %}
    {%  if user.type == 'Superuser' %}
        {% padding_menu_block 'Заполненность' '/reports/fillability/' SM %}
    {%  endif %}
{% endblock %}

odaybook/reports/templates/report_fillability.html
{% extends '~reports/page.html' %}

{% block js %}
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Переменная');
        data.addColumn('number', 'Значение');
        data.addRows(4);
        data.setValue(0, 0, 'Заполнено');
        data.setValue(0, 1, {{ all.filled }});
        data.setValue(1, 0, 'Не заполнено меньше 10 дней');
        data.setValue(1, 1, {{ all.not_filled }});
        data.setValue(2, 0, 'Не заполнено больше 10 дней');
        data.setValue(2, 1, {{ all.not_filled_from_10_to_15_days }});
        data.setValue(3, 0, 'Не заполнено больше 15 дней');
        data.setValue(3, 1, {{ all.not_filled_more_15_days }});

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, {width: 500, height: 300, title: '', reverseCategories: true});
      }
{% endblock %}

{% block content %}
    <form method="GET" action=".">
        Школа: {{ form.school }}
        <input type="submit" value="Показать">
        <a href="?export_to_csv=1" style="padding-left: 10px;">Экспортировать в CSV</a>
    </form>
    {% with hide_export_link=1 %}
        {% include 'report_form.html' %}
        <div id="chart_div" style=""></div>
    {% endwith %}
{% endblock %}

odaybook/reports/templates/report_form.html
{% load formater %}


<table class="table">
	<thead>
		{% for row in rows.get_header %}
            <th>{{ row }}</th>
        {% endfor %}
	</thead>
    <tbody>
        {% for row in rows.get_content %}
            <tr class="{% cycle '' 'gray' %}">
                {% for col in row %}
                    <td>
                        {{ col|number_format:2 }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
<p>
    {% if not hide_export_link %}
        <a href="?export_to_csv=1">Экспортировать в CSV</a>
    {% endif %}
</p>

odaybook/reports/templates/report_health.html
{% extends '~reports/page.html' %}

{% block content %}
    {% include 'report_form.html' %}
{% endblock %}

odaybook/reports/templates/report_marks.html
{% extends '~reports/page.html' %}

{% block  js_ready %}
    $("#id_start").datepicker($.datepicker.regional["ru"]);
    $("#id_end").datepicker($.datepicker.regional["ru"]);
    $( "#radio" ).buttonset();
{% endblock %}

{% load formater %}


{% block content %}
    <p>
        <a href="/reports/marks/?{{ params|urllibencode }}">Все</a> или <a href="/reports/marks/result/?{{ params|urllibencode }}">итоговые</a>.
    </p>
    <form method="get" action=".">
        <table class="table form">
            {% for field in pupilSelectForm %}
            <tr>
                <td class="label"><label for="{{ field.label }}">{{ field.label_tag }}:</label></td>
                <td>{{ field }}</td>
                <td>
                    {% if field.errors %}<div class="error_text">{{ field.errors }}</div>{% endif %}
                    {% if field.help_text %}<div class="help_text">{{ field.help_text}}</div>{% endif %}
                </td>
            </tr>
            {% endfor %}
        {% if marks and mode == 'all' %}
            {% for field in form %}
            <tr>
                <td class="label"><label for="{{ field.label }}">{{ field.label_tag }}:</label></td>
                <td>{{ field }}</td>
                <td>
                    {% if field.errors %}<div class="error_text">{{ field.errors }}</div>{% endif %}
                    {% if field.help_text %}<div class="help_text">{{ field.help_text}}</div>{% endif %}
                </td>
            </tr>
            {% endfor %}
        {% endif %}
            {% if pupilSelectForm.fields or mode == 'all' %}<tr><td colspan="2"><input type="submit" value="Показать"></td></tr>{% endif %}
        </table>
    </form>
    {% if marks %}
        {% include '~reports/marks.html' %}
    {% endif %}
{% endblock %}

odaybook/reports/templates/report_membershipchanges.html
{% extends '~reports/page.html' %}

{% block content %}
    <form method="GET" action=".">
        Фильтр по школе: {{ form.school }}
        <input type="submit" value="Фильтровать">
    </form>
 <table class="table">
	<thead>
        <th></th>
        <th>Дата</th>
		<th>Ученик</th>
		<th>Школа</th>
	</thead>
	{% for object in objects.object_list %}
		<tr class="{% cycle 'gray' '' %}">
            <td>
                {% if object.type == '-' %}
                    <img src="{{ MEDIA_URL }}/images/delete.png" />
                {% else %}
                    <img src="{{ MEDIA_URL }}/images/add.png" />
                {% endif %}
            </td>
            <td>{{ object.timestamp }}</td>
            <td>{{ object.pupil }}</td>
            <td>{{ object.school }}</td>
		</tr>
	{% empty %}
		<tr><td colspan="4">Событий нет</td></tr>
	{% endfor %}
</table>
{% include "helpers/paginator.html" %}
{% endblock %}

odaybook/reports/templates/report_order.html
{% extends '~reports/page.html' %}

{% block content %}
    {% include 'report_form.html' %}
{% endblock %}