odaybook/marks/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns

urlpatterns = patterns("odaybook.marks.views",
                       (r'^$', 'index'),
                       (r'set_current_subject/(?P<subject_id>\d+)', 'set_current_subject'),

                       (r'^subject/(?P<subject_id>\d+)/', 'marksView'),

                       )

odaybook/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
   (r'^chaining/', include('smart_selects.urls')),
   (r"^$", "odaybook.views.index"),
   (r"^grade/$", "odaybook.views.grade"),
   (r"^subjects/$", "odaybook.views.subjects"),
   (r"^teachers/$", "odaybook.views.teachers"),
   (r"^teachers/(?P<id>\d+)/$", "odaybook.views.teacher"),

   (r'^admin/doc/', include('django.contrib.admindocs.urls')),
   (r'^admin/(.*)', include(admin.site.urls)),

   (r'^accounts/', include('odaybook.userextended.urls')),
   (r'^marks/', include('odaybook.marks.urls')),
   (r'^curatorship/', include('odaybook.curatorship.urls')),
   (r'^administrator/', include('odaybook.userextended.urls')),
   (r'^attendance/', include('odaybook.attendance.urls')),
   (r'^reports/', include('odaybook.reports.urls')),
)

odaybook/marks/models.py
# -*- coding: UTF-8 -*-
'''
    Работа с оценками.
'''


from django.db import models
from odaybook.userextended.models import Pupil, Teacher, Subject, Grade, School

class Lesson(models.Model):
    '''
        Занятие. Содержит информацию об уроке. 
    '''
    teacher = models.ForeignKey(Teacher,
                                verbose_name = u'Учитель',
                                blank = True,
                                null = True)
    date = models.DateField(u'Дата')
    topic = models.CharField(u'Тема урока',
                             max_length = 200,
                             blank = True,
                             null = True)
    task = models.CharField(u'Домашнее задание',
                            max_length = 200,
                            blank = True,
                            null = True)
    subject = models.ForeignKey(Subject, verbose_name = u'Предмет')
    grade = models.ManyToManyField(Grade, verbose_name = u'Класс')
    file = models.FileField(verbose_name = u'Приложить файл',
                            null = True,
                            blank = True,
                            upload_to = 'lessons')
    resultdate = models.ForeignKey('ResultDate', null = True, blank = True)
    fullness = models.BooleanField(default = False)

    serialize_fields = ['id', 'teacher_id', 'date', 'topic',
                        'task', 'subject_id', 'grade']
    serialize_name = 'lesson'
    
    class Meta:
        ordering = ['-date']

    def save(self, safe = False, *args, **kwargs):
        if not safe and not self.fullness:
            if self.topic and Mark.objects.filter(lesson = self).count() > 4:
                self.fullness = True
        super(Lesson, self).save(*args, **kwargs)

class Mark(models.Model):
    '''
        Оценка или пропуск за 1 урок.
    '''
    pupil = models.ForeignKey(Pupil, verbose_name = u'Ученик')
    lesson = models.ForeignKey(Lesson, verbose_name = u'Занятие')
    mark = models.IntegerField(u'Отметка', blank = True, null = True)
    absent = models.BooleanField(u'Отсутствовал')
    date = models.DateTimeField(u'Дата выставления', auto_now_add = True)
    comment = models.TextField(u'Комментарий к отметке', blank = True)

    serialize_fields = ['id', 'pupil_id', 'lesson_id', 'mark', 'absent', 'date']
    serialize_name = 'mark'
    
    def get_type(self):
        '''
            Для выделение класса с помощью CSS.
        '''
        if self.absent:
            return "bad"
        elif self.mark < 3:
            return "bad"
        elif self.mark >= 4:
            return "good"
        else:
            return "normal"
    
    def __unicode__(self):
        if self.absent:
            return u'H'
        else:
            return unicode(self.mark)

    def save(self, *args, **kwargs):
        from odaybook.userextended.models import Notify
        if not self.lesson.fullness:
            if self.lesson.topic and Mark.objects.filter(lesson = self.lesson) > 4:
                self.lesson.fullness = True
                self.lesson.save(safe = True)
        super(Mark, self).save(*args, **kwargs)
        Notify.objects.filter(user = self.lesson.teacher, type = '1').delete()
    
    class Meta:
        ordering = ['-date']

class ResultDate(models.Model):
    '''
        Итоговый период. 
    '''
    school = models.ForeignKey(School, null = True, blank = True)
    name = models.CharField(max_length=255, verbose_name = u'Имя периода',
                            null = True, blank = True)
    date = models.DateField(verbose_name = u'Дата подведения итога')
    grades = models.ManyToManyField(Grade, verbose_name = u'Классы')

    def save(self, *args, **kwargs):
        pk = self.pk
        super(ResultDate, self).save(*args, **kwargs)
        if not self.school and not pk:
            for school in School.objects.all():
                ResultDate(school = school, name = self.name, date = self.date).save()

    class Meta:
        ordering = ['date']
    def __unicode__(self):
        return self.name

odaybook/marks/forms.py
# -*- coding: UTF-8 -*-
'''
    Большая часть форм реализованы общими средствами Django для работы с HTTP
'''

from datetime import date, timedelta

from django import forms

from models import Lesson
from odaybook.marks.models import ResultDate
from odaybook.userextended.models import Grade

class LessonForm(forms.ModelForm):
    '''
        Работа с уроком. Не факт, что используется.
    '''
    class Meta:
        model = Lesson
        fields = ['topic', 'task']

class StatForm(forms.Form):
    '''
        Универсальная форма для выбора диапазона дат статистики.
        Используется в различных приложениях.
    '''
    def __init__(self, *args, **kwargs):
        super(StatForm, self).__init__(*args, **kwargs)
        self.fields['start'].widget.format = '%d.%m.%Y'
        self.fields['end'].widget.format = '%d.%m.%Y'
    start = forms.DateField(('%d.%m.%Y', '%d.%m.%y'),
                            label = u'Дата начала периода',
                            initial = date.today() - timedelta(weeks = 2))
    end = forms.DateField(('%d.%m.%Y','%d.%m.%y'),
                          label = u'Дата окончания периода',
                          initial = date.today())


class ResultDateForm(forms.ModelForm):
    '''
        Форма для создания итоговых оценок.
    '''
    def __init__(self, school = None, *args, **kwargs):
        super(ResultDateForm, self).__init__(*args, **kwargs)
        self.school = school
        self.fields['grades'].widget = forms.CheckboxSelectMultiple()
        self.fields['grades'].help_text = ''
        self.fields['grades'].queryset = Grade.objects.filter(school = school)
        self.fields['date'].widget.format = '%d.%m.%Y'
        if not school:
            del self.fields['grades']
    class Meta:
        model = ResultDate
        fields = ['name', 'date', 'grades']
    def save(self):
        result = super(ResultDateForm, self).save(commit = False)
        result.school = self.school
        result.save()
        self.save_m2m()
        return result
    date = forms.DateField(('%d.%m.%y', '%d.%m.%Y',), label = u'Дата подведения итога')

odaybook/marks/views.py
# -*- coding: UTF-8 -*-
from datetime import date, timedelta

from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib import messages

from odaybook.userextended.models import Pupil, Subject, Grade
from odaybook.curatorship.models import Connection
from odaybook.attendance.models import UsalTimetable

from models import Lesson, Mark, ResultDate
from forms import LessonForm, StatForm

@login_required
def index(request):
    '''
        Очень обширная страница, необходимо сделать разделение. 
    '''
    render = {}
    if request.user.type == 'Parent':
        start = date.today() - timedelta(weeks = 2)
        end = date.today() + timedelta(days = 1)
        if request.method == 'GET':
            render['form'] = form = StatForm()
        else:
            render['form'] = form = StatForm(request.POST)
            if form.is_valid():
                start = form.cleaned_data['start']
                end = form.cleaned_data['end']

        render.update(request.user.current_pupil.get_all_marks(start, end))

    elif request.user.type == 'Teacher':
        import demjson

        if request.GET.get('set_current_grade', False):
            grade = get_object_or_404(Grade,
                                      id = request.GET.get('set_current_grade'))
            if grade not in request.user.grades.all():
                raise Http404(u'Нет такого класса')
            request.user.current_grade = grade
            request.user.save()
        
        render['lesson_form'] = LessonForm()
        if request.GET.get('set_lesson', False):
            lesson = get_object_or_404(Lesson,
                                       id = int(request.GET.get('lesson', 0)),
                                       teacher = request.user)
            form = LessonForm(request.GET, instance = lesson)
            if form.is_valid():
                form.save()
            return HttpResponse('ok')
        
        if request.GET.get('get_lesson_info', False):
            lesson = get_object_or_404(Lesson,
                                       id = int(request.GET.get('lesson', 0)),
                                       teacher = request.user)
            return HttpResponse(demjson.encode({'task': lesson.task or '',
                                                'topic': lesson.topic or ''}))
            
        
        if request.GET.get('set_mark', False):
            from templatetags.marks_chart import get_mark
            pupil = get_object_or_404(Pupil,
                                      id = int(request.GET.get('pupil', 0)),
                                      grade = request.user.current_grade)
            lesson = get_object_or_404(Lesson,
                                       id = int(request.GET.get('lesson', 0)),
                                       teacher = request.user)
            mark = unicode(request.GET.get('mark', 0)).lower()
            Mark.objects.filter(pupil = pupil, lesson = lesson).delete()
            m = Mark(pupil = pupil, lesson = lesson)
            tr_id = 'p-%d-%d' % (pupil.id, lesson.id)
            if mark not in ['1', '2', '3', '4', '5', 'n', u'н', '']:
                return HttpResponse(demjson.encode({'id': tr_id, 'mark': 'no'}))
            if mark == '':
                return HttpResponse(demjson.encode({'id': tr_id, 'mark': ''}))
            if mark in [u'n', u'н']:
                m.absent = True
            else:
                m.mark = int(mark)
            m.save()
            return HttpResponse(demjson.encode({'id': tr_id,
                                                'mark': get_mark(pupil, lesson),
                                                'mark_value': str(m).strip(),
                                                'mark_type': m.get_type()
                                                }, encoding = 'utf-8'))
        
        from pytils import dt
        if not request.user.current_grade:
            if request.user.get_grades():
                request.user.current_grade = request.user.get_grades()[0]
                request.user.save()
            else:
                messages.error(request, u'К вам не привязано классов')
                return HttpResponseRedirect('/')
        request.user.current_grade.get_pupils_for_teacher_and_subject(
                request.user, request.user.current_subject
        )
        
        try:
            day, month, year = request.GET.get('date', '').split('.')
            date_start = date(day = day, month = month, year = year)
        except ValueError:
            date_start = date.today()

        lessons_range = []
        render['monthes'] = monthes = {}
        for i in xrange(1, 13):
            monthes[i] = ('', 0)
        
        kwargs = {
            'subject': request.user.current_subject,
            'grade': request.user.current_grade
        }
        conn = Connection.objects.filter(teacher = request.user, **kwargs)
        if not conn:
            raise Http404('No connections')
        conn = conn[0]
        if conn.connection != '0':
            kwargs['group'] = conn.connection

        kwargs4lesson = {}
        for i in xrange(14, -1, -1):
            d = date_start - timedelta(days = i)
            kwargs['workday'] = str(d.weekday()+1)
            if UsalTimetable.objects.filter(**kwargs):
                kwargs4lesson = {'teacher': request.user,
                                 'date': d,
                                 'subject': request.user.current_subject}
                groups = {}
                for lesson in UsalTimetable.objects.filter(**kwargs):
                    groups[lesson.group] = groups.get(lesson.group, 0) + 1
                groups = groups.values()
                if Lesson.objects.filter(grade = request.user.current_grade, **kwargs4lesson).count() != max(groups):
                    for j in xrange(max(groups) - Lesson.objects.filter(**kwargs4lesson).count()):
                        t = Lesson(**kwargs4lesson)
                        t.save()
                        t.grade.add(request.user.current_grade)
                        t.save()
            resultdates = ResultDate.objects.filter(date = d, grades = request.user.current_grade)
            if resultdates:
                resultdate = resultdates[0]
                kwargs4lesson = {
                    'resultdate': resultdate,
                    'grade': request.user.current_grade,
                    'subject': request.user.current_subject,
                    'teacher': request.user
                }
                if not Lesson.objects.filter(**kwargs4lesson):
                    del kwargs4lesson['grade']
                    lesson = Lesson(topic = resultdate.name,
                                    date = resultdate.date,
                                    **kwargs4lesson)
                    lesson.save()
                    lesson.grade.add(request.user.current_grade)
                    lesson.save()

        if len(kwargs4lesson) == 0:
            raise Http404(u'Нет расписания')

        del kwargs4lesson['date']
        kwargs4lesson['date__gte'] = date_start - timedelta(days = 15)
        for lesson in Lesson.objects.filter(**kwargs4lesson).order_by('date'):
            monthes[lesson.date.month] = (dt.ru_strftime(u'%B', lesson.date),
                                          monthes[lesson.date.month][1] + 1)
            lessons_range.append(lesson)

        for i in monthes.keys():
            if monthes[i][1] == 0:
                del monthes[i]
        render['lessons'] = lessons_range
        
    return render_to_response(
            '~marks/%s/index.html' % request.user.type.lower(),
            render,
            context_instance = RequestContext(request))

@login_required
@user_passes_test(lambda u: u.type == 'Teacher')
def set_current_subject(request, subject_id):
    '''
        Установка текущего предмета учителя для работы с журналом.
    '''
    request.user.current_subject = Subject.objects.get(id = subject_id)
    request.user.save()
    next_url = request.GET.get('next', '/marks/').strip()
    return HttpResponseRedirect(next_url)

@login_required
def marksView(request, subject_id):
    '''
        Просмотр оценок по данному предмету. Для родительского интерфейса
    '''
    render = {}
    objects = Mark.objects.filter(
            pupil = request.user.current_pupil,
            lesson__subject = get_object_or_404(Subject, id=subject_id)
    ).order_by('-lesson__date')

    paginator = Paginator(objects, settings.PAGINATOR_OBJECTS)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        render['objects'] = paginator.page(page)
    except:
        render['objects'] = paginator.page(paginator.num_pages)

    render['paginator'] = paginator.num_pages - 1
    request.user.current_subject = int(subject_id)
    return render_to_response('~marks/pupil/marks.html',
                              render,
                              context_instance=RequestContext(request))

odaybook/marks/templates/teacher/delivery.html
{% extends 'page.html' %}

{% block padding %}
    <a href="/#sch{{ school.id }}">{{ school }}</a>
    <span>&rarr;</span>
    <h1>Создание рассылки</h1>
    <table><tr style="vertical-align: baseline;"><td>
  </td><td style="padding-left: 20px;">
  </td></tr></table>
{% endblock %}

{% block content %}
	{% include 'helpers/uniForm.html' %}
{% endblock %}

odaybook/marks/templates/teacher/deliveryPrint.html
<html>
	<head><title></title></head>
<body>
	{% for pupil in pupils %}
		<i>{{ pupil.school }}</i><br />
		<i>Ведомость успеваемости с {{ start|date:"d.m.Y" }} по {{ end|date:"d.m.Y" }}</i>
		<h1>{{ pupil }}</h1> 
		{% for subject in pupil.subjects %}
			{{ subject }}: {{ subject.marks|join:", " }}<br />
		{% endfor %}
		<br clear=all style='page-break-before:always'>
	{% endfor %}
</body>
</html>

odaybook/marks/templates/teacher/giveMark.html
{% extends 'marks/teacher/page.html' %}

{% block content %}
<form method="post" action=".">{% csrf_token %}
<table>
	{% for mark in marks %}
		<tr><td colspan="3">{{ mark.name }}</td></tr>
		{% for field in mark.form %}
		<tr>
			<td class="label"><label for="{{ field.label }}">{{ field.label_tag }}:</label></td>
			<td>{{ field }}</td>
			<td>
				{% if field.errors %}<div class="error_text">{{ field.errors }}</div>{% endif %}
				{% if field.help_text %}<div class="help_text">{{ field.help_text}}</div>{% endif %}
			</td>
		</tr>
		<tr><td></td><td></td><td></td></tr>
		{% endfor %}
	{% endfor %}
	<tr><td colspan="2"><input type="submit" name="send"></td></tr>
</table>
</form>
{% endblock %}

odaybook/marks/templates/teacher/gradeLessonList.html
{% extends 'marks/teacher/page.html' %}

{% block content %}
<table>
	{% for lesson in lessons %}
	<tr>
		<td>{{ lesson.date|date:"d.m.Y" }}</td>
		<td><a href="/marks/grade/{{ grade_id }}/{{ lesson.id }}/">{{ lesson.topic|default:"Тема не указана" }}</a></td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

odaybook/marks/templates/teacher/gradeList.html
{% extends 'marks/teacher/page.html' %}

{% block content %}
<table>
	{% for grade in grades %}
	<tr>
		<td><a href="/marks/grade/{{ grade.id }}/">{{ grade.long_name }}</a></td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

odaybook/marks/templates/teacher/gradeResult.html
{% extends 'marks/teacher/page.html' %}

{% block content %}
<form method="post" action".">{% csrf_token %}
<table>
	<tr><td colspan="3">
		<input type="submit" name="send" value="Выставить отметки" />
	</td></tr>
	{% for pupil in pupils %}
	<tr>
		<td>({{ pupil.sa|default:"н\а" }})</td>
		<td>{{ pupil.name }}</td>
		<td>{{ pupil.form.mark }}</td>
		<td>{% if pupil.form.mark.errors %}<div class="erorr_text">{{ pupil.form.mark.errors }}</div>{% endif %}</td>
	</tr>
	{% endfor %}
</table>
<input type="hidden" value="{{ grade }}" name="grade" />
<input type="hidden" value="{{ resultdate }}" name="resultdate" />
</form>	
{% endblock %}

odaybook/marks/templates/teacher/gradeResultList.html
{% extends 'marks/teacher/page.html' %}

{% block content %}
<form method="post" action="give/">{% csrf_token %}
<table>
	<tr>
		<td colspan="2">
			<select name="resultdate">
				{% for resultdate in resultdates %}
				<option value="{{ resultdate.id }}">{{ resultdate.get_period_display }}</option>
				{% endfor %}
			</select>
			<input type="submit" value="Выставить отметки" />
		</td>
	</tr>
	{% for grade in grades %}
	<tr>
		<td><input type="radio" name="grade" id="grade-{{ grade.id }}" value="{{ grade.id }}" /></td>
		<td><label for="grade-{{ grade.id }}">{{ grade.long_name }}</label></td>
	</tr>
	{% endfor %}
</table>
</form>	
{% endblock %}

odaybook/marks/templates/teacher/index.html
{% extends 'teacher/page.html' %}
{% load pytils_dt %}
{% load marks_chart %}

<script type="text/javascript">
	var lesson_id = 0;
</script>

{% block js_ready %}
lesson_id = 0;
	$('#dialog').dialog({
		autoOpen: false,
		width: 420,
		modal: true,
		buttons: {
			"Закрыть": function() { 
				$.get('?set_lesson=1&lesson=' + lesson_id, $('#lesson_form').serializeArray());
                if ($('#id_topic').val()!='') {
                    $('#lesson-' + lesson_id).removeClass('red');
                }
				$('#id_topic').val('');
				$('#id_task').val('');
				$(this).dialog("close");
				$('lesson_form').css('display', 'none');
			}, 
		},
		open: function(event, ui) {
			$.get('/marks/?get_lesson_info=1', {lesson: lesson_id}, function(data){
				$('#id_topic').val(data.topic);
				$('#id_task').val(data.task);
				$('#lesson_form').css('display', 'block');
			}, 'json');
			/*$('#dialog').children('p').append(lesson_id + '; ');*/
		}
	});
	
	$('.dialog_link').click(function(){
		lesson_id = $(this).attr('lesson');
		$('#dialog').dialog('open');
		return false;
	});
	

{% endblock %}

{% block padding %}
	{% if user.type == 'Teacher'%}
			<div id="sub-navigation">
			<div id="padding">
			{% for subject in subjects %}
				{% ifequal subject.id user.current_subject.id %}
					<h1>{{ subject.name }}</h1>
				{% else %}
					<a href="/marks/set_current_subject/{{ subject.id }}?next={{ next }}">{{ subject.name }}</a>
				{% endifequal %}
			{% endfor %}
			</div>
			</div>
	{% endif %}
	
{% endblock %}


{% block content %}

	<div id="dialog" title="Заполните информацию об уроке">
		<form action="." method="get" id="lesson_form" style="display: none;">
			<table>
				{{ lesson_form }}
			</table>
		</form>
	</div>

<table class="table mtable" style="margin-left: 0px;" id="marks">
	<tr><td style="vertical-align: top;">
		<table class="table">
			<thead>
				<tr>
					<td>Выберите класс:</td>
				</tr>
			</thead>
			<tbody>
				{% for gr in user.get_grades_for_marks %}
					<tr><td>
						<ul>
							<li>
                                {% if gr == user.current_grade %}
                                    {{ gr }}
                                {% else %}
                                    <a href="?set_current_grade={{ gr.id }}">{{ gr }}</a>
                                {% endif %}
                            </li>
						</ul>
					</td></tr>
				{% endfor %}
			</tbody>
		</table>
	</td>
	<td>

<div id="debug"></div>
<table class="table table_marks">
	<thead>
		<tr>
			<th style="border: none;"></th>
			{% for month, value in monthes.items %}
				<th style="border-bottom: none; border-right: 1px solid; border-left: 1px solid; text-align: center" colspan="{{ value.1 }}">{{ value.0 }}</th>
			{% endfor %}
		</tr>
		<tr>
		<th></td>
		{% for lesson in lessons %}
            {% if lesson.resultdate %}
                <th>{{ lesson.resultdate }}</th>
            {% else %}
                <th><a id="lesson-{{ lesson.id }}" href="#" class="ajax dialog_link{% if not lesson.topic %} red{% endif %}" lesson="{{ lesson.id }}">{{ lesson.date|date:"d" }}</a></th>
            {% endif %}
		{% endfor %}
	</tr></thead>
	<tbody>
		{% for pupil in user.current_grade.pupils %}
			<tr class="{% cycle 'gray' '' %}">
				<td><nobr>{{ pupil.fi }}</nobr></td>
				{% for lesson in lessons %}
					<td class="for-mark" mark="true" pupil="{{ pupil.id }}" lesson="{{ lesson.id }}" left="p-{{ pupil.id }}-{{ lesson|prev_date:lessons }}" right="p-{{ pupil.id }}-{{ lesson|next_date:lessons }}" up="p-{{ pupil|up_pupil:user.current_grade.pupils }}-{{ lesson.id }}" down="p-{{ pupil|down_pupil:user.current_grade.pupils }}-{{ lesson.id }}" next="p-{{ pupil|first_pupil:user.current_grade.pupils }}-{{ lesson|next_date:lessons }}" id="p-{{ pupil.id }}-{{ lesson.id }}">
						{{ pupil|get_mark:lesson }}
					</td>
				{% endfor %}
			</tr>
		{% endfor %}
	</tbody>
</table>

	</td>
	</tr>
</table>
<script type="text/javascript">
	var active = null;
	function hide_inputs(){
        $('td.for-mark').each(function(){
            $(this).children('input').remove();
            if ($(this).attr('mark')!='true'){
                $(this).html('<div class="' + $(this).attr('mark-class') + '">' + $(this).attr('mark') + '</div>');
            }
        });
    }
	function init_mark_input(id){
		mark = $('#' + id.replace('m-', '')).children('div');
		if(mark.html()){
			$('#' + id.replace('m-', '')).attr('mark-class', mark.attr('class'));
			$('#' + id.replace('m-', '')).attr('mark', mark.html());
			$('#' + id.replace('m-', '')).append('<input type="input" class="mark" id="' + id + '" value="' + mark.html() + '" />');
		}
		else{
			$('#' + id.replace('m-', '')).attr('mark', '');
			$('#' + id.replace('m-', '')).append('<input type="input" class="mark" id="' + id + '" value="" />');
		}
		$('#' + id.replace('m-', '')).children('div').html('');
		$('#' + id).focus();
		active = id;
	}

	function register_chart_event(key){
		$('td.for-mark').bind('keydown', key, function(){
			mark = $(this);
			mark_id = $(this).attr('id');
			if( mark.attr('mark') != mark.children('input').val() ){
				$.get('?', {pupil: $(this).attr('pupil'), lesson: $(this).attr('lesson'), 'mark': mark.children('input').val(), 'set_mark': 1}, function(data){
					if (data.mark!='no'){
						$('#' + data.id).html(data.mark);
						$('#' + data.id).attr('mark', 'true');
						$('#' + data.id).attr('mark-class', 'mark-' + data.mark_type);
					}
				}, 'json');
			}
			
			if (key == 'Return') {
				key = 'down';
			}
			new_id = 'm-' + $(this).attr(key);
			if(key == 'down' & $(this).attr('right').search('None')==-1 & $(this).attr(key).search('None')!=-1){
				new_id = 'm-' + $(this).attr('next');
			}
			if(new_id.search('None')==-1){
				hide_inputs(); 
				if( mark.attr('mark') != mark.children('input').val() ){
					$(this).html('<div class="' + $(this).attr('mark-class') + '">' + $(this).attr('mark') + '</div>');
				}
				else{
					$(this).html('<div class="' + $(this).attr('mark-class') + '">...</div>');
				
				}
				init_mark_input(new_id);
			}
		});
	}

	register_chart_event('up');
	register_chart_event('down');
	register_chart_event('left');
	register_chart_event('right');
	register_chart_event('Return');

	$('td.for-mark').click(function(){
		id = 'm-' + $(this).attr('id')
		if (active){
			hide_inputs();
		}
		init_mark_input(id);
	});
</script>
{% endblock %}

odaybook/marks/templates/teacher/lesson.html
{% extends 'marks/teacher/page.html' %}
{% block content %}
<form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
	<fieldset>
	<legend>Урок</legend>
	<table class="fieldset">
		{% for field in form %}
		<tr>
			<td class="label"><label for="{{ field.label }}">{{ field.label_tag }}:</label></td>
			<td>{{ field }}</td>
			<td>
				{% if field.errors %}<div class="error_text">{{ field.errors }}</div>{% endif %}
				{% if field.help_text %}<div class="help_text">{{ field.help_text}}</div>{% endif %}
			</td>
		</tr>
		{% endfor %}
	</table>
	<input type="submit" value="Сохранить">
	</fieldset>
</form>
{% endblock %}

odaybook/marks/templates/teacher/page.html
{% extends 'page.html' %}