odaybook/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
   (r'^chaining/', include('smart_selects.urls')),
   (r"^$", "odaybook.views.index"),
   (r"^grade/$", "odaybook.views.grade"),
   (r"^subjects/$", "odaybook.views.subjects"),
   (r"^teachers/$", "odaybook.views.teachers"),
   (r"^teachers/(?P<id>\d+)/$", "odaybook.views.teacher"),

   (r'^admin/doc/', include('django.contrib.admindocs.urls')),
   (r'^admin/(.*)', include(admin.site.urls)),

   (r'^accounts/', include('odaybook.userextended.urls')),
   (r'^marks/', include('odaybook.marks.urls')),
   (r'^curatorship/', include('odaybook.curatorship.urls')),
   (r'^administrator/', include('odaybook.userextended.urls')),
   (r'^attendance/', include('odaybook.attendance.urls')),
   (r'^reports/', include('odaybook.reports.urls')),
)

odaybook/userextended/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls.defaults import patterns
from django.contrib.auth.views import login, logout, password_change, \
    password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from forms import PasswordChangeForm

urlpatterns = patterns("odaybook.userextended.views",
                       (r'^$', 'index'),
                       (r'login', login, {'template_name': 'login.html'}),
                       (r'logout', logout, {'next_page': '/'}),
                       (r'password_change', password_change, {'template_name': 'change_password.html',
                                                              'post_change_redirect': '/',
                                                              'password_change_form': PasswordChangeForm,
                                                              }),
                       (r'password_reset/$', password_reset, {'template_name': 'password_reset.html',}),
                       (r'password_reset_done/$', password_reset_done, {'template_name': 'password_reset_done.html'}),
                       (r'password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
                        {'template_name': 'password_reset_confirm.html',}),

                       (r'password_reset_complete/$', password_reset_complete,
                        {'template_name': 'password_reset_complete.html',}),

                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/$', 'objectList'),
                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/add/$', 'objectEdit', {'mode': 'add'}),
                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/edit/(?P<id>\d+)/$', 'objectEdit', {'mode': 'edit'}),
                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/delete/(?P<id>\d+)/$', 'objectEdit', {'mode': 'delete'}),

                       # дубляж ради filter_id очень некрасив
                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/(?P<filter_id>\d+)/$', 'objectList'),
                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/(?P<filter_id>\d+)/add/$', 'objectEdit', {'mode': 'add'}),
                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/(?P<filter_id>\d+)/edit/(?P<id>\d+)/$',
                        'objectEdit', {'mode': 'edit'}),
                       (r'^uni/(?P<app>\w+).(?P<model>\w+)/(?P<filter_id>\d+)/delete/(?P<id>\d+)/$',
                        'objectEdit', {'mode': 'delete'}),

                       (r'^baseuser/$', 'objectList', {'app': 'userextended', 'model': 'Clerk'}),
                       (r'^baseuser/add/$', 'baseUserObjectEdit', {'mode': 'add'}),
                       (r'^baseuser/edit/(?P<id>\d+)/$', 'baseUserObjectEdit', {'mode': 'edit'}),
                       (r'^baseuser/delete/(?P<id>\d+)/$', 'baseUserObjectEdit', {'mode': 'delete'}),
                       (r'^baseuser/set/(?P<id>\d+)/$', 'baseUserObjectEdit', {'mode': 'set_right'}),
                       (r'^baseuser/dismiss/(?P<id>\d+)/$', 'baseUserObjectEdit', {'mode': 'dismiss'}),
                       (r'^baseuser/reset_password/(?P<id>\d+)/$', 'baseUserObjectEdit', {'mode': 'reset_password'}),
                       
                       (r'^uni/userextended.Grade/(?P<filter_id>\d+)/import/$', 'import_grade'),
                       (r'^uni/userextended.Teacher/(?P<filter_id>\d+)/import/$', 'import_teacher'),
                       (r'^uni/userextended.Pupil/(?P<filter_id>\d+)/import/$', 'import_pupil'),

                       (r'^set_role/(?P<role_id>\d+)/$', 'set_role'),
                       (r'^set_current_pupil/(?P<id>\d+)/$', 'set_current_pupil'),

                       (r'^appendrole/$', 'clerkAppendRole'),
                       (r'^register-clerk/$', 'register_clerk'),

                       (r'^ajax/get/subject/(?P<id>\d+)/$', 'get_subject'),
                       
                       (r'^uni/userextended.Pupil/(?P<filter_id>\d+)/exclude/(?P<id>\d+)/$', 'exclude_pupil'),
                       (r'^uni/userextended.Pupil/(?P<school>\d+)/connect/$', 'connect_pupil'),
                       )

odaybook/attendance/models.py
# -*- coding: UTF-8 -*-

from django.db import models
from django.conf import settings

from odaybook.userextended.models import School

class RingTimetable(models.Model):
    u'''
        Заготовка для расписания звонков.
    '''
    number = models.CharField(u"Номер урока", max_length = 1, choices = settings.LESSON_NUMBERS)
    start = models.TimeField(u'Начало урока')
    end = models.TimeField(u'Окончание урока')
    school = models.ForeignKey(School)
    class Meta:
        abstract = True

class UsalRingTimetable(RingTimetable):
    u'''
        Регулярное расписание звонков, повторяющиеся каждую неделю.
    '''
    workday = models.CharField(u"День недели", max_length = 1, choices = settings.WORKDAYS)

class SpecicalRingTimetable(RingTimetable):
    u'''
        Заготовка специального расписания звонков. Нигде не используется
    '''
    date = models.DateField(u"Дата")

class Timetable(models.Model):
    u'''
        Заготовка расписания занятий.
    '''
    from odaybook.userextended.models import Grade, Subject
    grade = models.ForeignKey(Grade)
    number = models.CharField(u"Номер урока", max_length = 2, choices = settings.LESSON_NUMBERS)
    subject = models.ForeignKey(Subject, verbose_name = u"Предмет")
    room = models.CharField(u"Кабинет", max_length = 25, null = True, blank = True)
    group = models.CharField(u"Группа", max_length = 1, choices = ( ('1', '1 группа'), ('2', '2 группа') ))
    school = models.ForeignKey(School)
    class Meta:
        abstract = True
        ordering = ['number']

class UsalTimetable(Timetable):
    u'''
        Регулярное расписание занятий, повторяющиеся каждую неделю.
    '''
    workday = models.CharField(u"День недели", max_length = 1, choices = settings.WORKDAYS)

class SpecicalTimetable(Timetable):
    u'''
        Заготовка специального расписания занятий. Нигде не используется
    '''
    date = models.DateField(u"Дата")

class Holiday(models.Model):
    u'''
        Заготовка каникулярных периодов. Нигде не используется
    '''
    name = models.CharField(u"Имя", max_length = 255)
    start = models.DateField(u"Дата начала")
    end = models.DateField(u"Дата окончания")
    school = models.ForeignKey(School)

odaybook/userextended/models.py
# -*- coding: UTF-8 -*-

from datetime import timedelta, datetime, date
import pytils
import random
import logging

from django.db import models
from django.db.models import Q
from django.db.models.aggregates import Avg
from django.contrib.auth.models import User, UserManager
from django.db.models.signals import post_save, post_syncdb
from django.dispatch import receiver

from odaybook.utils import PlaningError
from odaybook import settings

logger = logging.getLogger(__name__)

class School(models.Model):
    '''Модель для школы'''
    name = models.CharField(u"Имя учебного заведения", max_length = 250)
    saturday = models.BooleanField(verbose_name = u'Шестидневка', default = True)
    url = models.URLField(verbose_name = u'Веб-сайт', null = True, blank = True)
    address = models.CharField(verbose_name = u'Адрес школы', max_length = 255)
    phone = models.CharField(verbose_name = u'Телефон школы', max_length = 255)
    max_mark = models.IntegerField(verbose_name = u'Максимальный балл', default = 5)
    gapps_use = models.BooleanField(verbose_name = u'Использовать Google Apps', default = False)
    gapps_login = models.CharField(max_length = 255, default = '', verbose_name = u'Логин для Google Apps',
                                   blank = True, null = True)
    gapps_password = models.CharField(max_length = 255, default = '', verbose_name = u'Пароль для Google Apps',
                                      blank = True, null = True)
    gapps_domain = models.CharField(max_length = 255, default = '', verbose_name = u'Домен для Google Apps',
                                    blank = True, null = True)
    private_domain = models.CharField(max_length = 255, verbose_name = u'Система привязана к домену',
                                      null = True, blank = True)
    private_salute = models.CharField(max_length = 255, verbose_name = u'Персональное приветствие',
                                      null = True, blank = True)

    serialize_fields = ['id', 'name', 'saturday']
    serialize_name = 'school'
    
    def __init__(self, *args, **kwargs):
        '''
            Подгрузка списка доступных настроек. Необходимо в списке школ панели администратора.
        '''
        
        from odaybook.curatorship.models import Connection
        super(School, self).__init__(*args, **kwargs)
        
        grades = Grade.objects.filter(school = self).count() > 0
        teachers = Teacher.objects.filter(school = self).count() > 0
        marks = Connection.objects.filter(teacher__school = self).count() > 0
        show = {}
        show['teachers'] = show['staff'] = show['subjects'] = show['grades'] = show['options'] = True
        show['pupils'] = grades
        show['resultdates'] = grades
        show['connections'] = teachers
        show['deliveryes'] = marks
        show['timetables'] = teachers
        show['marks'] = marks
        self.show = show

    def __unicode__(self):
        return self.name
    
    def get_workdays(self):
        '''
            Список числовых значений учебных дней.
        '''
        if self.saturday:
            days = 6
        else:
            days = 5
        return range(1, days+1)

    def get_workdays_tuple(self):
        '''Возвращает кортедж из кириллических названий учебных дней школы.'''
        result = ()
        for d in settings.WORKDAYS:
            if int(d[0]) in self.get_workdays():
                result += (d, )
        return result

    def get_workdays_dict(self):
        '''
            Возвращает словарь учебных дней школы, в которых числовому значению ключа соответстветствует
            кортедж формата (ключ, кириллическое_название)
        '''
        result = {}
        for d in settings.WORKDAYS:
            if int(d[0]) in self.get_workdays():
                result[int(d[0])] = d
        return result

    def save(self, *args, **kwargs):
        '''
            Начальная инициализация школы. Добавление предметов
        '''
        pk = self.pk
        super(School, self).save(*args, **kwargs)
        if not pk:
            subjects = [u'Русский язык', u'Физкультура', u'Информатика', 
                        u'Обществознание', u'Литература', u'География', 
                        u'Химия', u'Физика', u'Биология', u'История', 
                        u'ОБЖ', u'Алгебра', u'Геометрия', u'Ин. яз.']
            
            for subject in subjects:
                Subject(school = self, name = subject).save()

class Option(models.Model):
    '''
        Модель для указания дополнительных настроек как для школы, так и для системы вцелом.
    '''
    key = models.CharField(max_length = 255, verbose_name = u'Ключ')
    key_ru = models.CharField(max_length = 255, verbose_name = u'Настройка')
    value = models.CharField(max_length = 255, verbose_name = u'Значение', null = True, blank = True)
    school = models.ForeignKey(School, verbose_name = u'Школа', null = True, blank = True)

def SystemInitCallback(sender, **kwargs):
    '''
        Callback после syncdb для создания заранее существующих настроек.
    '''
    options = [
        {'key': 'vnc_link', 'key_ru': u'Ссылка на приложение ТП', 'value': ''},
    ]
    for option in options:
        Option.objects.get_or_create(**option)

post_syncdb.connect(SystemInitCallback)

class Grade(models.Model):
    '''Классы в школах'''
    number = models.IntegerField(verbose_name = u'Порядковый номер')
    long_name = models.CharField(u"Длинное имя", max_length = 100)
    small_name = models.CharField(u"Короткое имя", max_length = 10, blank = True)
    school = models.ForeignKey(School, verbose_name = "Школа")

    serialize_fields = ['id', 'long_name', 'school_id']
    serialize_name = 'grade'
    
    def __unicode__(self):
        if self.number:
            return "%d %s" % (self.number, self.long_name)
        else:
            return self.long_name

    def get_subjects(self):
        '''
            Получение списка всех предметов, которые ведутся в этом классе
        '''
        from odaybook.curatorship.models import Connection
        return [c.subject for c in Connection.objects.filter(grade = self)]

    def get_subjects_queryset(self):
        u'''
            Получение queryset всех предметов, которые ведут в этом классе
        '''
        return Subject.objects.filter(id__in = [s.id for s in self.get_subjects()])
        
    def delete(self):
        if not Pupil.objects.filter(grade = self):
            for teacher in Teacher.objects.filter(grade = self):
                teacher.grade = None
                teacher.save()
            for teacher in Teacher.objects.filter(grades = self):
                teacher.grades.remove(self)
                teacher.save()
            super(Grade, self).delete()
        else:
            raise PlaningError(u"В классе числятся ученики")
        
    def save(self, *args, **kwargs):
        self.long_name = self.long_name.lower()
        self.small_name = self.small_name.lower()
        super(Grade, self).save(*args, **kwargs)

    class Meta:
        ordering = ['number']
    
    def get_pupils_for_teacher_and_subject(self, teacher, subject):
        '''
            В свойство pupils записываются ученики, у которых преподаватель teacher ведёт предмет subject.
        '''
        from odaybook.curatorship.models import Connection
        conn = Connection.objects.filter(teacher = teacher, grade = self, subject = subject)
        if not conn:
            raise PlaningError(u'нет учеников')
        conn = conn[0]
        if conn.connection == '0':
            self.pupils = Pupil.objects.filter(grade = self)
        else:
            pupil_connections = PupilConnection.objects.filter(pupil__grade = self,
                                                               subject = subject,
                                                               value = conn.connection)
            self.pupils = Pupil.objects.filter(id__in = [c.pupil.id for c in pupil_connections])

class Subject(models.Model):
    '''Учебная дисциплина'''
    name = models.CharField(u"Наименование", max_length = 100)
    school = models.ForeignKey(School, verbose_name = "Школа")
    groups = models.CharField(max_length = 1, blank = True, null = True, verbose_name = u'Количество групп')


    def __unicode__(self):
        return self.name
    def delete(self):
        for teacher in Teacher.objects.filter(subjects = self):
            teacher.subjects.remove(self)
            teacher.save()
        super(Subject, self).delete()

    def get_groups(self):
        '''Возвращает список из номеров групп для данного предмета'''
        return range(1, int(self.groups)+1)

    class Meta:
        ordering = ['name']

class SearchManager(models.Manager):
    '''
        Универсальный менеджер для поиска по произвольным полям модели. Заменяет стандартный objects.

        При инициализации передается список полей для поиска.
    '''
    def __init__(self, search_fields = []):
        self.search_fields = search_fields
        models.Manager.__init__(self)

    def search(self, search_string):
        '''
            Собственно поиск.

            search_string - строка для поиска.
        '''
        search_query_list = [Q(**{s + '__icontains': search_string}) for s in self.search_fields]
        search_query = reduce(lambda x, y: x | y, search_query_list)
        return self.filter(search_query)

class ClerkManager(UserManager, SearchManager):
    '''Аггрегация всего и вся'''
    pass

class BaseClerk(models.Model):
    '''
        Поля, присыщие всем пользовательским моделям, включая концентрациооную BaseUser.
    '''
    middle_name = models.CharField(u"Отчество", max_length = 30)
    cart = models.CharField(u'Карта', max_length = 10, null = True, blank = True)
    phone = models.CharField(max_length = 20, verbose_name = u'Номер телефона', null = True, blank = True)
    roles = models.ManyToManyField('BaseUser', null = True, blank = True,

odaybook/userextended/templates/change_password.html
{% extends 'page.html' %}

{% block content %}
  {% include 'helpers/uniForm.html' %}

{% endblock %}

odaybook/userextended/templates/clerk.html
{% extends 'page.html' %}

{% block padding %}
    <a href="/accounts/baseuser/">Аккаунты</a>
    <span>&rarr;</span>
    <h1>Редактирование</h1>
{% endblock %}


{% block content %}
	{% include 'helpers/uniForm.html' %}
{% endblock %}

odaybook/userextended/templates/clerkAppendRole.html
{% extends 'page.html' %}

{% block padding %}
    <a href="/administrator/uni/userextended.School/#sch{{ schoolObj.id }}">{{ schoolObj }}</a>
    <span>&rarr;</span>
    <a href="/administrator/uni/userextended.Teacher/{{ schoolObj.id }}/">Учителя</a>
    <span>&rarr;</span>
    {% if step == '1' %}
        <h1>Проверка пользователя</h1>
    {% endif %}
{% endblock %}


{% block content %}
    {% if step == '1' %}
        {% if error %}
            <p>Ошибка: {{ error|lower }}</p>
        {% endif %}
        {% if clerk %}
            <form action="?step=2&school={{ school }}" method="POST">
                <input type="hidden" name="username" value="{{ username }}" />
                <p>Результат запроса: {{ clerk.fio }}</p>
                <p>
                    <input type="submit" value="Добавить пользователя" />
                </p>
            </form>
        {% else %}
            <form action="?step=1&school={{ school }}" method="POST">
                <table>
                    <tr>
                        <td>Введите имя пользователя</td>
                        <td><input type="text" name="username" value="{{ username }}" /> </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="submit" value="Проверить" />
                        </td>
                    </tr>
                </table>
            </form>
        {% endif %}
    {% endif %}
{% endblock %}

odaybook/userextended/templates/connect_pupil.html
{% extends 'page.html' %}

{% block padding %}
    <a href="/administrator/uni/userextended.School/#sch{{ school.id }}">{{ school }}</a>
    <span>&rarr;</span>
    <a href="/administrator/uni/userextended.Pupil/{{ school.id }}/">Ученики</a>
    <span>&rarr;</span>
    <h1>Редактирование</h1>
{% endblock %}

{% block js_ready %}
    pupil_id = 0;
	$('#dialog').dialog({
		autoOpen: false,
		width: 420,
        height: 140,
		modal: true,
		buttons: {
			"Зачислить": function() {
                if (pupil_id){
                    $('#pupil').val(pupil_id);
                    $('#grade_form').submit();
//				$.get('?set_lesson=1&lesson=' + lesson_id, $('#lesson_form').serializeArray());
//				$('#id_topic').val('');
//				$('#id_task').val('');
//				$(this).dialog("close");
//				$('lesson_form').css('display', 'none');
                }
			},
		},
//		open: function(event, ui) {
//			$.get('/marks/?get_lesson_info=1', {lesson: lesson_id}, function(data){
//				$('#id_topic').val(data.topic);
//				$('#id_task').val(data.task);
//				$('#lesson_form').css('display', 'block');
//			}, 'json');
//			/*$('#dialog').children('p').append(lesson_id + '; ');*/
//		}
	});
	$('.dialog_link').click(function(){
		pupil_id = $(this).attr('pupil');
		$('#dialog').dialog('open');
		return false;
	});

{% endblock %}

{% block content %}
	<div id="dialog" title="Клас для зачисления">
		<form action="." method="post" id="grade_form">
            <input type="hidden" name="pupil" id="pupil" />
            <select name="grade">
                {% for grade in grades %}<option value="{{ grade.id }}">{{ grade }}</option>{% endfor %}
            </select>
		</form>
	</div>
    <p>
        {% if pupils %}
            Выберите ученика к зачислению.
        {%  else %}
            Нет учеников к зачислению.
        {% endif %}
    </p>
    <table>
        <tr>
            {% for pupil in pupils %}
                <td>{{ pupil }}</td>
                <td><a href="#" pupil="{{ pupil.id }}" class="dialog_link">зачислить</a></td>
            {% endfor %}
        </tr>
    </table>
    {%  comment  %}
    <table class="no-hover"><tr><td>
	{% if not pupil %}
        {% if not_found %}
            <b>Ученик не найден</b>
        {% endif %}
        <form action="." method="GET">
        <fieldset>
            <legend>Введите логин ученика</legend>
            <table>
                <tr>
                    <td>
                        <input type="text" name="username" />
                    </td>
                </tr>
                <tr>
                    <td><input type="submit" value="Искать" /></td>
                </tr>
            </table>
        </fieldset>
        </form>
    {% else %}
        <form action="." method="POST">
        <input type="hidden" name="username" value="{{ pupil.username }}" />
        <fieldset>
            <legend>Подтвердите информацию</legend>
            <table>
                <tr>
                    <td>Имя: </td>
                    <td>{{ pupil.fio }}</td>
                </tr>
                <tr>
                    <td>Класс: </td>
                    <td>
                        <select name="grade">
                            {% for grade in grades %}
                                <option value="{{ grade.id }}">{{ grade }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><input type="submit" value="Добавить" /></td>
                </tr>
            </table>
        </fieldset>
        </form>

    {% endif %}
    </td></tr></table>
    {%  endcomment %}
{% endblock %}

odaybook/userextended/templates/grade.html
{% extends 'page.html' %}

{% block padding %}
    <a href="/administrator/uni/userextended.School/#sch{{ school.id }}">{{ school }}</a>
    <span>&rarr;</span>
    <a href="/administrator/uni/userextended.Grade/{{ school.id }}/">Классы</a>
    <span>&rarr;</span>
    <h1>Редактирование</h1>
{% endblock %}


{% block content %}
	{% include 'helpers/uniForm.html' %}
{% endblock %}

odaybook/userextended/templates/notify_1_mail.html
Здравствуйте, {{ username.fio }}.<br /><br>

Напоминаем Вам о необходимости регулярного заполнения дневника.

Данные для входа в систему:<br />
Логин: {{ user.username }}<br />

Форма для входа в в Панель Управления размещена в правом верхнем углу на сайте http://sochi.edu.ru/

Убедительная просьба, заполните пожалуйста журнал.

Желаем успехов!

odaybook/userextended/templates/notify_2_mail.html
{# Это неиспользуемый треш #}

Здравствуйте, {{ username.fio }}.<br /><br>

Напоминаем Вам о необходимости регулярного заполнения дневника.

Данные для входа в систему:<br />
Логин: {{ user.username }}<br />

Форма для входа в в Панель Управления размещена в правом верхнем углу на сайте http://sochi.edu.ru/

Убедительная просьба, заполните пожалуйста журнал.

Желаем успехов!

odaybook/userextended/templates/teacher.html
{% extends 'page.html' %}

{% block padding %}
    <a href="/administrator/uni/userextended.School/#sch{{ school.id }}">{{ school }}</a>
    <span>&rarr;</span>
    <a href="/administrator/uni/userextended.Teacher/{{ school.id }}/">Учителя</a>
    <span>&rarr;</span>
    <h1>Редактирование</h1>
{% endblock %}

{% block content %}
<form method="post" action=".">{% csrf_token %}
<table class="table"><tr><td>
	<fieldset>
		<legend>Личная информация</legend>
		<table>
			<tr>
				<td class="label"><label for="id_last_name">Фамилия:</label></td>
				<td>{{ form.last_name }}</td>
				<td>
					{% if form.last_name.errors %}<div class="error_text">{{ form.last_name.errors }}</div>{% endif %}
					{% if form.last_name.help_text %}<div class="help_text">{{ form.last_name.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_first_name">Имя:</label></td>
				<td>{{ form.first_name }}</td>
				<td>
					{% if form.first_name.errors %}<div class="error_text">{{ form.first_name.errors }}</div>{% endif %}
					{% if form.first_name.help_text %}<div class="help_text">{{ form.first_name.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_middle_name">Отчество: </label></td>
				<td>{{ form.middle_name }}</td>
				<td>
					{% if form.middle_name.errors %}<div class="error_text">{{ form.middle_name.errors }}</div>{% endif %}
					{% if form.middle_name.help_text %}<div class="help_text">{{ form.middle_name.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_email">{{ form.email.label }}: </label></td>
				<td>{{ form.email }}</td>
				<td>
					{% if form.email.errors %}<div class="error_text">{{ form.email.errors }}</div>{% endif %}
					{% if form.email.help_text %}<div class="help_text">{{ form.email.help_text }}</div>{% endif %}
				</td>
			</tr>
		</table>
	</fieldset>
	</td></tr><tr><td>
	<fieldset>
		<legend>Преподавание</legend>
		<table>
			<tr>
				<td class="label"><label for="id_subjects">Предметы:</label></td>
				<td>{{ form.subjects }}</td>
				<td>
					{% if form.subjects.errors %}<div class="error_text">{{ form.subjects.errors }}</div>{% endif %}
					{% if form.subjects.help_text %}<div class="help_text">{{ form.subjects.help_text }}</div>{% endif %}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="id_grades">Классы:</label></td>
				<td>{{ form.grades }}</td>
				<td>
					{% if form.grades.errors %}<div class="error_text">{{ form.grades.errors }}</div>{% endif %}
					{% if form.grades.help_text %}<div class="help_text">{{ form.grades.help_text }}</div>{% endif %}
				</td>
			</tr>
		</table>
	</fieldset>
	</td></tr><tr><td>
	<fieldset>
		<legend>Другое</legend>
		<table>
      <tr>
        <td class="label"><label for="id_grade">Классное руководство:</label></td>
        <td>{{ form.grade }}</td>
        <td>
          {% if form.grade.errors %}<div class="error_text">{{ form.grade.errors }}</div>{% endif %}
          {% if form.grade.help_text %}<div class="help_text">{{ form.grade.help_text }}</div>{% endif %}
        </td>
      </tr>
      <tr>
        <td class="label"><label for="id_edu_admin">Администратор школы:</label></td>
        <td>{{ form.edu_admin }}</td>
        <td>
          {% if form.edu_admin.errors %}<div class="error_text">{{ form.edu_admin.errors }}</div>{% endif %}
          {% if form.edu_admin.help_text %}<div class="help_text">{{ form.edu_admin.help_text }}</div>{% endif %}
        </td>
      </tr>
      {% if form.cart %}
			<tr>
				<td class="label"><label for="id_cart">Номер карты: </label></td>
				<td>{{ form.cart }}
				<td>
					{% if form.cart.errors %}<div class="error_text">{{ form.cart.errors }}</div>{% endif %}
					{% if form.cart.help_text %}<div class="help_text">{{ form.cart.help_text }}</div>{% endif %}
				</td>
			</tr>
		{% endif %}
		</table>
	</fieldset>
	</td></tr><tr><td>
		<input type="submit" value="Сохранить" />
	</td></tr>
</table>
</form>
{% endblock %}